In [6]:
# creating the id array
import random
import numpy as np
np.random.seed(15)
arr1d=np.random.randint(15,45,8)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [7]:
print(arr1d)

[23 36 27 20 38 15 43 42]


# 1-D array Indexing

In [17]:
arr1d[2]
arr1d[7]
arr1d[0]

np.int32(27)

np.int32(42)

np.int32(23)

# 2-D array Indexing

- arr[i] -- to get single row with index numbers i
- arr[[i,j,k...]] -- to get multiple rows with index numbers i,j,k...
- arr[i,j] -- to get the single value present in ith row and jth column
- arr[i][j] -- to get the single value present in ith row and jth column


In [36]:
np.random.seed(52)
arr2=np.random.randint(10,150,(9,8))
arr2

array([[ 21,  23,  96, 149, 107,  43,  15,  26],
       [149,  64,  52,  64,  49,  32,  81,  49],
       [145,  73,  30,  44,  74,  73,  75, 111],
       [ 92, 144, 138, 100, 134,  48,  40, 130],
       [ 59,  19,  27, 115,  84, 128,  35,  20],
       [127,  22,  19,  26,  32,  38,  65, 136],
       [ 40, 133, 111,  87,  59,  69,  65,  69],
       [145,  94,  17,  27, 111,  24, 107, 115],
       [ 46,  21,  88, 106, 115, 120,  73, 128]], dtype=int32)

In [44]:
# Get the first row
arr2[0]
# Get the 3rd and 4th rows (index - 2,3)
arr2[[2,3]]
# Get the value from 1st row, 4th column
arr2[1,[4]]
arr2[1,4]
# Get the value from 4th row, 2nd column
arr2[[3,1]]
# Getthe value from 3rd row, 8th column

# Get the value from 5th row, 2th column
# Get the value from 2nd row, 4th column



array([ 21,  23,  96, 149, 107,  43,  15,  26], dtype=int32)

array([[145,  73,  30,  44,  74,  73,  75, 111],
       [ 92, 144, 138, 100, 134,  48,  40, 130]], dtype=int32)

array([49], dtype=int32)

np.int32(49)

array([[ 92, 144, 138, 100, 134,  48,  40, 130],
       [149,  64,  52,  64,  49,  32,  81,  49]], dtype=int32)

## 3-D array Indexing 
- arr[i] -- to get enitre single 2D array with index number i
- arr[[i,j,k...]] -- to get multiple 2D arrays with index numbers i,j,k...
- arr[i,j] --  from the ith 2D array get a single row with index number j
- arr[i][j] --  from the ith 2D array get a single row with index number j
- arr[i,j,k] --  from the ith 2D array get a single integer value from jth row and kth column
- arr[i][j][k] --  from the ith 2D array get a single integer value from jth row and kth column



In [61]:
arr_3d=np.random.randint(10,99,(3,4,5))
arr_3d

array([[[44, 73, 61, 84, 47],
        [63, 59, 81, 25, 77],
        [82, 50, 96, 96, 79],
        [98, 88, 53, 50, 31]],

       [[85, 34, 73, 60, 88],
        [14, 63, 79, 27, 68],
        [80, 36, 92, 23, 41],
        [95, 45, 36, 77, 36]],

       [[83, 76, 67, 34, 85],
        [41, 70, 13, 61, 47],
        [16, 73, 54, 17, 79],
        [56, 75, 70, 94, 63]]], dtype=int32)

In [62]:
#Aceessing the single 2d array
arr_3d[0]  #single 2d array

array([[44, 73, 61, 84, 47],
       [63, 59, 81, 25, 77],
       [82, 50, 96, 96, 79],
       [98, 88, 53, 50, 31]], dtype=int32)

In [76]:
#Aceessing the first row
arr_3d[[0,2]] #mutliple 2d arrays 

array([[[[44, 73, 61, 84, 47],
         [63, 59, 81, 25, 77],
         [82, 50, 96, 96, 79],
         [98, 88, 53, 50, 31]],

        [[83, 76, 67, 34, 85],
         [41, 70, 13, 61, 47],
         [16, 73, 54, 17, 79],
         [56, 75, 70, 94, 63]]]], dtype=int32)

In [81]:
arr_3d[0,1]# [ith row and jth column

array([63, 59, 81, 25, 77], dtype=int32)

In [82]:
arr_3d[2,1]

array([41, 70, 13, 61, 47], dtype=int32)

In [83]:
#acessing single elements
arr_3d[0,0,0]

np.int32(44)

In [84]:
arr_3d[1,3,4]

np.int32(36)

# Slicing

- Slicing of Arrays
- Slicing allows to extract portions of an array or select a subset of an existing array to generate new arrays. For slicing a sequence of numbers separated by colons (:) within square brackets.

`arr[row_start:row_end, col_start:col_end]`  



`Using step - arr[row_start:row_end:step, col_start:col_end:step]`

## 1-D Array Slicing 

In [85]:
arr1d

array([23, 36, 27, 20, 38, 15, 43, 42], dtype=int32)

In [86]:
arr1d[0:2]

array([23, 36], dtype=int32)

In [87]:
arr1d[0:]

array([23, 36, 27, 20, 38, 15, 43, 42], dtype=int32)

In [88]:
arr1d[:-1]

array([23, 36, 27, 20, 38, 15, 43], dtype=int32)

In [89]:
arr1d[-9:-1]

array([23, 36, 27, 20, 38, 15, 43], dtype=int32)

In [90]:
arr1d[::]

array([23, 36, 27, 20, 38, 15, 43, 42], dtype=int32)

In [93]:
arr1d[2:8:2]

array([27, 38, 43], dtype=int32)

In [94]:
arr1d[::-1] #reverse an array


array([42, 43, 15, 38, 20, 27, 36, 23], dtype=int32)

## 2-D Array Slicing 

In [96]:
arr2

array([[ 21,  23,  96, 149, 107,  43,  15,  26],
       [149,  64,  52,  64,  49,  32,  81,  49],
       [145,  73,  30,  44,  74,  73,  75, 111],
       [ 92, 144, 138, 100, 134,  48,  40, 130],
       [ 59,  19,  27, 115,  84, 128,  35,  20],
       [127,  22,  19,  26,  32,  38,  65, 136],
       [ 40, 133, 111,  87,  59,  69,  65,  69],
       [145,  94,  17,  27, 111,  24, 107, 115],
       [ 46,  21,  88, 106, 115, 120,  73, 128]], dtype=int32)

In [97]:
#slicing the rows and columns

arr2[0:2] #rows

array([[ 21,  23,  96, 149, 107,  43,  15,  26],
       [149,  64,  52,  64,  49,  32,  81,  49]], dtype=int32)

In [98]:
arr2[:,0:2] #columns

array([[ 21,  23],
       [149,  64],
       [145,  73],
       [ 92, 144],
       [ 59,  19],
       [127,  22],
       [ 40, 133],
       [145,  94],
       [ 46,  21]], dtype=int32)

In [99]:
arr2[0:2,2:] #colums starting from 2

array([[ 96, 149, 107,  43,  15,  26],
       [ 52,  64,  49,  32,  81,  49]], dtype=int32)

In [102]:
arr2[0:2,-3:] #last three 

array([[43, 15, 26],
       [32, 81, 49]], dtype=int32)

In [103]:
arr2[0,2:5]

array([ 96, 149, 107], dtype=int32)

In [106]:
arr2[0:4:2]

array([[ 21,  23,  96, 149, 107,  43,  15,  26],
       [145,  73,  30,  44,  74,  73,  75, 111]], dtype=int32)

In [108]:
arr2[0:4:2,::2]

array([[ 21,  96, 107,  15],
       [145,  30,  74,  75]], dtype=int32)

In [117]:
# reversing a array
arr2[::-1,::-1] #reversed

array([[128,  73, 120, 115, 106,  88,  21,  46],
       [115, 107,  24, 111,  27,  17,  94, 145],
       [ 69,  65,  69,  59,  87, 111, 133,  40],
       [136,  65,  38,  32,  26,  19,  22, 127],
       [ 20,  35, 128,  84, 115,  27,  19,  59],
       [130,  40,  48, 134, 100, 138, 144,  92],
       [111,  75,  73,  74,  44,  30,  73, 145],
       [ 49,  81,  32,  49,  64,  52,  64, 149],
       [ 26,  15,  43, 107, 149,  96,  23,  21]], dtype=int32)

In [116]:
arr2 #original

array([[ 21,  23,  96, 149, 107,  43,  15,  26],
       [149,  64,  52,  64,  49,  32,  81,  49],
       [145,  73,  30,  44,  74,  73,  75, 111],
       [ 92, 144, 138, 100, 134,  48,  40, 130],
       [ 59,  19,  27, 115,  84, 128,  35,  20],
       [127,  22,  19,  26,  32,  38,  65, 136],
       [ 40, 133, 111,  87,  59,  69,  65,  69],
       [145,  94,  17,  27, 111,  24, 107, 115],
       [ 46,  21,  88, 106, 115, 120,  73, 128]], dtype=int32)

In [118]:
arr2.T

array([[ 21, 149, 145,  92,  59, 127,  40, 145,  46],
       [ 23,  64,  73, 144,  19,  22, 133,  94,  21],
       [ 96,  52,  30, 138,  27,  19, 111,  17,  88],
       [149,  64,  44, 100, 115,  26,  87,  27, 106],
       [107,  49,  74, 134,  84,  32,  59, 111, 115],
       [ 43,  32,  73,  48, 128,  38,  69,  24, 120],
       [ 15,  81,  75,  40,  35,  65,  65, 107,  73],
       [ 26,  49, 111, 130,  20, 136,  69, 115, 128]], dtype=int32)

### Extracting the single value 

In [114]:
arr2[0:4,2]

array([ 96,  52,  30, 138], dtype=int32)

In [ ]:
# if you want to extract the single value use indexing or below method

In [115]:
arr2[0:4,2][2]

np.int32(30)

## 3-D Array Slicing 

In [123]:
arr_3d

array([[[44, 73, 61, 84, 47],
        [63, 59, 81, 25, 77],
        [82, 50, 96, 96, 79],
        [98, 88, 53, 50, 31]],

       [[85, 34, 73, 60, 88],
        [14, 63, 79, 27, 68],
        [80, 36, 92, 23, 41],
        [95, 45, 36, 77, 36]],

       [[83, 76, 67, 34, 85],
        [41, 70, 13, 61, 47],
        [16, 73, 54, 17, 79],
        [56, 75, 70, 94, 63]]], dtype=int32)

In [124]:
arr_3d[::,::,::]

array([[[44, 73, 61, 84, 47],
        [63, 59, 81, 25, 77],
        [82, 50, 96, 96, 79],
        [98, 88, 53, 50, 31]],

       [[85, 34, 73, 60, 88],
        [14, 63, 79, 27, 68],
        [80, 36, 92, 23, 41],
        [95, 45, 36, 77, 36]],

       [[83, 76, 67, 34, 85],
        [41, 70, 13, 61, 47],
        [16, 73, 54, 17, 79],
        [56, 75, 70, 94, 63]]], dtype=int32)

In [134]:
arr_3d[0:1,:,:]  #single 2d arr

array([[[44, 73, 61, 84, 47],
        [63, 59, 81, 25, 77],
        [82, 50, 96, 96, 79],
        [98, 88, 53, 50, 31]]], dtype=int32)

In [135]:
arr_3d[0:1,0:1,:]  #single row 

array([[[44, 73, 61, 84, 47]]], dtype=int32)

In [137]:
arr_3d[0:1,0:1,0:1]  #single element 

array([[[44]]], dtype=int32)

In [138]:
arr_3d[0:1,0:1,0:2]  # double elements

array([[[44, 73]]], dtype=int32)

In [139]:
arr_3d[:,:2,:2]

array([[[44, 73],
        [63, 59]],

       [[85, 34],
        [14, 63]],

       [[83, 76],
        [41, 70]]], dtype=int32)

In [140]:
arr_3d[:,:3,:2]

array([[[44, 73],
        [63, 59],
        [82, 50]],

       [[85, 34],
        [14, 63],
        [80, 36]],

       [[83, 76],
        [41, 70],
        [16, 73]]], dtype=int32)

In [141]:
arr_3d[:,0:3,0:3]

array([[[44, 73, 61],
        [63, 59, 81],
        [82, 50, 96]],

       [[85, 34, 73],
        [14, 63, 79],
        [80, 36, 92]],

       [[83, 76, 67],
        [41, 70, 13],
        [16, 73, 54]]], dtype=int32)

In [ ]:
# More Array operations