### import numpy as np
lst=[[5,6,7],[2,3,5],[1,3,2]]
arr1=np.array(lst,dtype=np.float32)

In [128]:
print(arr1)

[[5. 6. 7.]
 [2. 3. 5.]
 [1. 3. 2.]]


In [23]:
print(np.__version__)

2.3.1


In [24]:
arr2=np.diag(arr1)

In [25]:
print(arr2)

[2. 3. 7.]


In [30]:
lst=[i for i in range(1,10)]
arr1=np.array(lst)

In [32]:
arr1=arr1.reshape(9,1)

In [35]:
arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1 np.arange(Start, End, Increment)

In [17]:
import numpy as np
arr2=np.arange(1,500,10)
# it will sequencely arranges the all the numbers 
print(arr2.reshape(1,5,10))

[[[  1  11  21  31  41  51  61  71  81  91]
  [101 111 121 131 141 151 161 171 181 191]
  [201 211 221 231 241 251 261 271 281 291]
  [301 311 321 331 341 351 361 371 381 391]
  [401 411 421 431 441 451 461 471 481 491]]]


## ii. Arrays with linspace()
*The linspace() function generates an array with evenly spaced values between specified start and end values, using a specified number of elements.*

Syntax:

np.linspace(Start, End, Number of elements)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
# so we can make or create the evenly seperated elements by
arr2=np.linspace(1,10,10) # so it will evenly divides the 10 numbers by 1
print(arr2) 
print('--'*30)
print()
arr2=np.linspace(1,10,15) # so it will evenly divides the 10 numbers by 15
print(arr2) 
print('--'*30)
print()

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
------------------------------------------------------------

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
------------------------------------------------------------



In [35]:
arr2=np.linspace(1,10,20) # so it will evenly divides the 10 numbers by 20
print(arr2) 
print('--'*30)
arr2=np.linspace(1,10,20) # so it will evenly divides the 1,11  numbers by 25 2d elements 
arr2d=np.linspace(1,11,25).reshape(5,5)
print(arr2d) 
print('--'*30)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
------------------------------------------------------------
[[ 1.          1.41666667  1.83333333  2.25        2.66666667]
 [ 3.08333333  3.5         3.91666667  4.33333333  4.75      ]
 [ 5.16666667  5.58333333  6.          6.41666667  6.83333333]
 [ 7.25        7.66666667  8.08333333  8.5         8.91666667]
 [ 9.33333333  9.75       10.16666667 10.58333333 11.        ]]
------------------------------------------------------------


## iii. Zero Array
The zeros() function, generates an array with the specified dimensions and data type that is filled with zeros.

In [13]:
arrz=np.zeros(125)

In [14]:
print(arrz)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]


In [15]:
arrz.reshape(5,5,5)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

## iv. One Array
The ones() function, generates an array with the specified dimensions and data type that is filled with ones.

In [7]:
import numpy as np
a1=np.ones(15)   # we cannot give @D direct shape here

In [8]:
a1.reshape(3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## v. Full Array
The full() function, generates an array with the specified dimensions and data type that is filled with specified number

In [7]:
af=np.full(125,5)

In [8]:
print(af.reshape(5,5,5))

[[[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]]


In [14]:
#Identity array that is used to generate array with identical diagonal

import numpy as np
idarr=np.identity(5)
print(idarr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
#we can not give 2-D shape here directly 
idarr2=np.identity(5,5)

TypeError: Cannot interpret '5' as a data type

In [16]:
#diag it is used to get the diagnal
diarr=np.diag(idarr)
print(diarr)

[1. 1. 1. 1. 1.]


In [27]:
lst=[[2,3,5],[1,3,2],[5,6,7]]
arr1=np.array(lst)
print(f' array 1 is \n',arr1)
print(f'\n diagnal of  1 is ',np.diag(arr1))

print(f' \n "diagnal(diagnal(arr1))"  of  1 is \n',np.diag(np.diag(arr1)))

 array 1 is 
 [[2 3 5]
 [1 3 2]
 [5 6 7]]

 diagnal of  1 is  [2 3 7]
 
 "diagnal(diagnal(arr1))"  of  1 is 
 [[2 0 0]
 [0 3 0]
 [0 0 7]]


In [22]:
np.diag(diarr)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
import numpy as np
arr1=np.arange(1,15,3)
print('1d array is :',arr1) #if you give the diag of diag or something zero array with dignal of arr2 values
print('After digonal : ')
print(np.diag(arr1))
print('After digonal(diag) : ')
print(np.diag(np.diag(arr1)))

1d array is : [ 1  4  7 10 13]
After digonal : 
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  7  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 13]]
After digonal(diag) : 
[ 1  4  7 10 13]


## vii. Eye Array
The eye() function, returns an array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one.

In [10]:
arri=np.eye(4,k=0)
print("defauly eye array is :\n",arri) #4,k=0

defauly eye is :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
arri=np.eye(5,k=2)
print("5,k=2 :\n",arri) #4,k=0

5,k=2 :
 [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
arri=np.eye(5,k=-2)
print("5,k=-2 :\n",arri) #4,k=0

5,k=-2 :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [21]:
arri=np.eye(7,8,k=-1)
print("user defined shape :\n",arri) #4,k=0

user defined shape :
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]


In [31]:
print(arr1)

[[2. 3. 5.]
 [1. 3. 2.]
 [5. 6. 7.]]


In [114]:
dict1={}
lat=[]
for i in range(len(arr1)):
    sum1=0
    print(arr1[i])
    for j in range(len(arr1[i])):
        sum1=sum1+arr1[i][j]
    dict1[i]=sum1
max_row_index = max(dict1, key=dict1.get)
print(f"maximum sum row is {arr1[max_row_index]} and sum is {dict1[max_row_index]}")

[5. 6. 7.]
[2. 3. 5.]
[1. 3. 2.]
maximum sum row is [5. 6. 7.] and sum is 18.0


In [ ]:
dict1 = {}
arr1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

for i in range(len(arr1)):
    sum1 = 0
    print(arr1[i])
    for j in range(len(arr1[i])):
        sum1 += arr1[i][j]
    dict1[i] = sum1

max_row_index = max(dict1, key=dict1.get)
print(f"maximum sum row is {arr1[max_row_index]} and sum is {dict1[max_row_index]}")


In [111]:
print(lst)

[[5, 6, 7], [2, 3, 5], [1, 3, 2], np.float32(5.0), np.float32(11.0), np.float32(18.0), np.float32(2.0), np.float32(5.0), np.float32(10.0), np.float32(1.0), np.float32(4.0), np.float32(6.0), np.float32(18.0), np.float32(10.0), np.float32(6.0)]


In [130]:
count=arr1.size
sum1=0
for i in range(len(arr1)):
    for j in range(len(arr1[i])):
        sum1=sum1+arr1[i][j]
        mean=sum1//count
        if(arr1[i,j]<mean):
            arr1[i,j]=0
        else:
            arr1[i,j]=1



In [131]:
print(sum1)

34.0


In [132]:
mean

np.float32(3.0)

In [133]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 0.]], dtype=float32)

In [129]:
arr1

array([[5., 6., 7.],
       [2., 3., 5.],
       [1., 3., 2.]], dtype=float32)

In [134]:
Random

NameError: name 'ran' is not defined