## kumkapalla chidvilas

### NumPy Basics

### What is NumPy and why is it used in Python?
NumPy stands for Numerical Python.
It is mainly used to create and work with arrays, especially multidimensional arrays.
NumPy is widely used to perform arithmetic operations on arrays efficiently.
It provides built-in functions that make mathematical and statistical operations faster and easier when working with large data.


In [58]:
# How do you install NumPy in your system?
!pip install numpy
import numpy
print(numpy.__version__)

2.3.1


In [59]:
# Write a code to create a 1D NumPy array from a list.
lst=[1,2,3,4,5,6,7,8,9]
arr1=np.array(lst)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [60]:
# How to find the data type of elements in a NumPy array?4
# by using the .dtype
print(arr1.dtype)

int64


In [61]:
# Write a code to create a 2D array using NumPy.
lst2=[[1,2],[3,4],[5,6]]
arr2d=np.array(lst2)
print(arr2d)

[[1 2]
 [3 4]
 [5 6]]


## Reshape

In [62]:
#Write code to reshape a 1D array of 12 elements into a 3x4 array.
import random as rd
arr12=rd.sample(range(10,150),12)
print(np.reshape(arr12,(4,3)))

[[ 93  96  41]
 [106  73  26]
 [110  82 101]
 [122 111  94]]


In [63]:
#What will happen if you try to reshape an array with incompatible dimensions?
# it will throw an errors
# -> arrays can be only reshaped if shape is the factors of size

print(np.reshape(arr12,(4,3,2))) #  <<---------- Throws the error

ValueError: cannot reshape array of size 12 into shape (4,3,2)

In [64]:
#Convert a 2x6 array into a 3x4 array using reshape.
arr12=np.array(rd.sample(range(1250,1500),12)).reshape(2,6)
print("2x6 Array : \n", arr12)
print("3x4 after reshaping Array : \n", arr12.reshape(3,4))

2x6 Array : 
 [[1424 1260 1294 1454 1335 1413]
 [1333 1332 1370 1281 1291 1330]]
3x4 after reshaping Array : 
 [[1424 1260 1294 1454]
 [1335 1413 1333 1332]
 [1370 1281 1291 1330]]


In [65]:
#How to reshape a 3x3 array into a 1D array?
import random as rd
lst=rd.sample(range(1500,1980),9)
arr2d=np.array(lst)
arr2d=arr2d.reshape(3,3)
print("3x3 Array : \n", arr2d)
print("\n\n 3x3 after reshaping into 1d  Array : \n\n", arr2d.reshape(9,))

3x3 Array : 
 [[1821 1634 1605]
 [1509 1595 1597]
 [1709 1641 1806]]


 3x3 after reshaping into 1d  Array : 

 [1821 1634 1605 1509 1595 1597 1709 1641 1806]


In [66]:
#What is the use of -1 in reshape function?
# reshape(1,-1)----> it will reshapes the array  1 row x n columns
#reshape(-1,1) ----> it will reshapes the array to n rows x 1 column

lst=[range(1,10)]
arr2d=np.array(lst)
print('reshape(1,-1) of matrix gives',arr2d.reshape(1,-1))
print('reshape(-1,1) of matrix gives',arr2d.reshape(-1,1))

reshape(1,-1) of matrix gives [[1 2 3 4 5 6 7 8 9]]
reshape(-1,1) of matrix gives [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## Resize

In [67]:
#Differentiate between reshape and resize in NumPy.
#	reshape() returns a new array with a different shape without modifying the original array.
#	resize() modifies the original array and can also change its size by adding or removing elements.

arr_reshape=np.arange(1,101,9)
arr_resize=np.arange(1,101,9)
print('reshaping the array : \n',arr_reshape.reshape(4,3))
print('Original array after reshape : \n',arr_reshape)  #it doesnt modifies the original 1-D array
print()
print('resize the array : \n',arr_resize.resize(4,3))
print('Original array after resize : \n',arr_resize)  #it doesnt modifies the original 1-D array

reshaping the array : 
 [[  1  10  19]
 [ 28  37  46]
 [ 55  64  73]
 [ 82  91 100]]
Original array after reshape : 
 [  1  10  19  28  37  46  55  64  73  82  91 100]

resize the array : 
 None
Original array after resize : 
 [[  1  10  19]
 [ 28  37  46]
 [ 55  64  73]
 [ 82  91 100]]


In [68]:
#Write code to resize a 2x3 array to 3x2
import random
arr2_3=np.array(random.sample(range(10,60),6)).reshape(2,3)
arr2_3.resize(3,2)
print(arr2_3)

[[23 49]
 [41 56]
 [47 48]]


In [69]:
#What happens if you resize an array to a larger size?#
arr2_3.resize(3,5) 
print(arr2_3) #-> if you directly reshaping 2-D array it will throws an eroror 

ValueError: cannot resize this array: it does not own its data

In [70]:
#so if you use 1-D array it will not throw any error  ->   It adds zeors at last
arr1=np.arange(1,81,9)
arr1.resize(3,5)
print(arr1)


[[ 1 10 19 28 37]
 [46 55 64 73  0]
 [ 0  0  0  0  0]]


## Write code to resize an array in-place.
* resize() modifies the original array in-place.
* To resize an array in-place, you must ensure it's a base array (not a view). 
* It works only if the array is not a view (e.g., don't use .reshape() directly before resize()).

## Explain how resize affects the original array.
resize it will modifies the entire base array instread of creating new array

## Slicing for 1D and 2D

In [71]:
#Slice the first five elements from a 1D array
print('actual array :' ,arr1)
print('first five elements from a 1D array',arr1[:5])

actual array : [[ 1 10 19 28 37]
 [46 55 64 73  0]
 [ 0  0  0  0  0]]
first five elements from a 1D array [[ 1 10 19 28 37]
 [46 55 64 73  0]
 [ 0  0  0  0  0]]


In [72]:
#How to reverse a 1D array using slicing?
print('actual array :' ,arr1)
print('reversed elements from a 1D array',arr1[::-1])

actual array : [[ 1 10 19 28 37]
 [46 55 64 73  0]
 [ 0  0  0  0  0]]
reversed elements from a 1D array [[ 0  0  0  0  0]
 [46 55 64 73  0]
 [ 1 10 19 28 37]]


In [73]:
#Extract the second column from a 2D array using slicing.#
arr12=np.array(arr12)
arr12=arr12.reshape(3,4)
print('actual 2D array :\n' ,arr12)
print(' second column from a 2D array \n\n',arr12[:,1])

actual 2D array :
 [[1424 1260 1294 1454]
 [1335 1413 1333 1332]
 [1370 1281 1291 1330]]
 second column from a 2D array 

 [1260 1413 1281]


In [74]:
#Get the last two rows from a 2D array.
arr12=np.array(arr12)
arr12=arr12.reshape(3,4)
print('actual 2D array :\n' ,arr12)
print('  last two rows from a 2D array \n\n',arr12[1:])

actual 2D array :
 [[1424 1260 1294 1454]
 [1335 1413 1333 1332]
 [1370 1281 1291 1330]]
  last two rows from a 2D array 

 [[1335 1413 1333 1332]
 [1370 1281 1291 1330]]


In [78]:
#Write code to slice a 3x3 matrix to get a 2x2 top-left submatrix.
arr12=np.array(arr12)
arr12=arr12.reshape(3,4)
print('actual 2D array :\n\n ' ,arr12)
print(' \n3x3 matrix to get a 2x2 top-left submatrix.\n\n',arr12[:2])


actual 2D array :

  [[1424 1260 1294 1454]
 [1335 1413 1333 1332]
 [1370 1281 1291 1330]]
 
3x3 matrix to get a 2x2 top-left submatrix.

 [[1424 1260 1294 1454]
 [1335 1413 1333 1332]]


## Type Casting

In [79]:
#Convert a float NumPy array to integer type.
arrf=np.linspace(100,999,16)
arrf=arrf.reshape(4,4)
print('float array is \n\n', arrf)
narr=np.array(arrf,dtype=np.int16)
print('\n convertening float to int is \n\n',narr)

float array is 

 [[100.         159.93333333 219.86666667 279.8       ]
 [339.73333333 399.66666667 459.6        519.53333333]
 [579.46666667 639.4        699.33333333 759.26666667]
 [819.2        879.13333333 939.06666667 999.        ]]

 convertening float to int is 

 [[100 159 219 279]
 [339 399 459 519]
 [579 639 699 759]
 [819 879 939 999]]


In [93]:
#How to change the data type of a NumPy array using astype()?
# -> astype() it will creates the new array where the original array remains unchanged
# -> dtype it will directly modifies the type of the original array
print('array before converting the data type to float  \n',chtype)
arr2=arr12.astype(str)
print('array After converting the data type to float  \n',arr2,arr2.dtype)
print('original array  \n',chtype,f'remains Unchanged->',arr12.dtype)

array before converting the data type to float  
 [[1424. 1260. 1294. 1454.]
 [1335. 1413. 1333. 1332.]
 [1370. 1281. 1291. 1330.]]
array After converting the data type to float  
 [['1424' '1260' '1294' '1454']
 ['1335' '1413' '1333' '1332']
 ['1370' '1281' '1291' '1330']] <U21
original array  
 [[1424. 1260. 1294. 1454.]
 [1335. 1413. 1333. 1332.]
 [1370. 1281. 1291. 1330.]] remains Unchanged-> int64


In [94]:
#Write code to convert an integer array to string type
print('int array is \n\n', narr)
print('\n convertening int array  to string type \n\n',np.array(narr,dtype='U4'))

int array is 

 [[100 159 219 279]
 [339 399 459 519]
 [579 639 699 759]
 [819 879 939 999]]

 convertening int array  to string type 

 [['100' '159' '219' '279']
 ['339' '399' '459' '519']
 ['579' '639' '699' '759']
 ['819' '879' '939' '999']]


## Why might you want to change the data type of an array?
* we want to change the data type of to convert the data acc to our usage
* To save memory (e.g., float64 → float32)
* To perform specific operations (e.g., converting strings to integers)

In [128]:
#What is the default data type of np.array([1.5, 2.3])?
#above array default type is float
arr9=np.array([1.5, 2.3])
print(" default data type of np.array([1.5, 2.3]) :" ,arr9.dtype)

 default data type of np.array([1.5, 2.3]) : float64


## Questions on arange

In [131]:
#Create an array with values from 0 to 9 using arange.
arrA1=np.arange(0,10)
print(arrA1)

[0 1 2 3 4 5 6 7 8 9]


In [133]:
#How to generate an array from 10 to 20 with a step of 2 using arange?
arrA2=np.arange(10,21)
print(arrA2)

[10 11 12 13 14 15 16 17 18 19 20]


In [134]:
#What will be the output of np.arange(5, 1, -1)?
print(np.arange(5, 1, -1))

[5 4 3 2]


In [135]:
#Create an array of even numbers between 2 and 20 using arange.
print(np.arange(2,21,2))

[ 2  4  6  8 10 12 14 16 18 20]


In [136]:
#Write code to generate an array from 0.5 to 2.5 with a step of 0.5 using arange.
print(np.arange(0.5,2.5,0.5))

[0.5 1.  1.5 2. ]


## NumPy Random Generator


In [143]:
#Generate a 1D array of 5 random integers between 0 and 10.
import random as rd
arrr=np.array(rd.sample(range(0,10),5))
print('1D array of 5 random integers between 0 and 10 is :',arrr)

1D array of 5 random integers between 0 and 10 is : [3 5 4 1 9]


In [146]:
#Create a 3x3 matrix with random float values between 0 and 1.
import random as rd
arrr2=np.linspace(0,1,9).reshape(3,3)
print(' 3x3 matrix with random float values between 0 and 1 :\n',arrr2)

 3x3 matrix with random float values between 0 and 1 :
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [158]:
#Set the seed value to 42 and generate 5 random numbers.
import random as rd
rd.seed(42)    #it will always prints [81 14  3 94 35] untill seed is presemnt
arrr3=np.array(rd.sample(range(0,99),5))
print('seed value to 42 and generate 5 random numbers :',arrr3)

seed value to 42 and generate 5 random numbers : [81 14  3 94 35]


In [97]:
#Write code to randomly shuffle a NumPy array.
import random as rd
arrr3=np.array(rd.sample(range(0,99),16)).reshape(4,4)
print(arrr3)

[[28 94 23 61]
 [67 20 82 12]
 [16 85 38 57]
 [50 58 14 46]]


In [106]:

#How to generate a normal distribution of values using NumPy?
import numpy as np

data = np.random.normal(loc=0, scale=1, size=10)
print(data)

[-0.76631289  0.44270174  0.53629027  0.76650135 -0.45188946 -0.03938834
  0.53499077  1.66772472  0.2096109  -1.09149318]


## np.zeros, np.full, np.identity, np.eye()

In [9]:
#Create a 2x3 array filled with zeros.
import numpy as np
arrz=np.zeros(6).reshape(2,3)
arrz

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#Create a 3x3 array filled with the number 7 using np.full.
arrf=np.full(9,7).reshape(3,3)
arrf

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [15]:
#Generate a 4x4 identity matrix.
arri=np.identity(4)
print(arri)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## What is the difference between np.eye and np.identity?
* np.identity(n) creates a square identity matrix only.

* np.eye(N, M, k) is more flexible — allows non-square matrices and shifting the diagonal using k.

In [17]:
#Create a 3x3 matrix with ones on the diagonal and zeros elsewhere using np.eye.
arri=np.eye(3)
print(arri)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## fliplr, flipud, flip, rot90

In [101]:
#Write code to flip a 2D array left to right.
arr=np.array(rd.sample(range(0,99),9)).reshape(3,3)
print(f"original arr is :\n",arr)
flipped_lr = np.fliplr(arr)
print(f"flipped  arr is :\n",flipped_lr)

original arr is :
 [[12 71 53]
 [18 49 50]
 [56 19 69]]
flipped  arr is :
 [[53 71 12]
 [50 49 18]
 [69 19 56]]


In [102]:
#Flip a 3x3 matrix upside down.
flipped_ud = np.flipud(arr)
print(flipped_ud)

[[56 19 69]
 [18 49 50]
 [12 71 53]]


In [103]:
#How to reverse all rows in a 2D array?
reversed_rows = arr[:, ::-1]
print(reversed_rows)

[[53 71 12]
 [50 49 18]
 [69 19 56]]


In [104]:
#Write code to rotate a 2D array 90 degrees counter-clockwise.
rotated_ccw = np.rot90(arr)
print(rotated_ccw)

[[53 50 69]
 [71 49 19]
 [12 18 56]]


In [105]:
#Explain the use of np.flip and how it differs from flipud or fliplr.
np.flip(arr)         
np.flip(arr, axis=0)  
np.flip(arr, axis=1)

array([[53, 71, 12],
       [50, 49, 18],
       [69, 19, 56]])