# NumPy Daily Task - Problem Solving Questions

In [38]:
#Create a NumPy array of shape (4, 5) with values from 0 to 19. Reshape it to (2, 10) and print its shape, size, and data type.
import numpy as np
arr=np.arange(0,20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [63]:
#2. Create a 3D array of shape (2, 3, 4) filled with numbers from 1 to 24. Write code to get:
  # - The second 2D matrix
  # - The last element of each 2D matrix
arr3d=np.arange(1,25).reshape(2,3,4)
print("3D matrix \n",arr3d)
print("Accessing second 2D matrix \n",arr3d[1])
print("Accessing second 2D matrix ",arr3d[1][-1,-1])

3D matrix 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Accessing second 2D matrix 
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Accessing second 2D matrix  24


In [80]:
#Create a 1D array with 12 elements and reshape it into a 3x4 array using reshape. Now change it to 4x3 using resize and observe the difference.
#-> it will returns the new copy of reshaped raay
#-> it will modifes the given array 
#-> if you put the more that correct size it will adds the zeros 
import random 
arr1d=np.random.randint(50,99,12)
print("1D array is  \n",arr1d)

print("\n reshape it into a 3x4 array using reshape \n",arr1d.reshape(3,4))
arr1d.resize(4,3)
print("\n change it to 4x3 using resize \n",arr1d)

1D array is  
 [57 75 81 75 82 79 68 55 69 98 79 96]

 reshape it into a 3x4 array using reshape 
 [[57 75 81 75]
 [82 79 68 55]
 [69 98 79 96]]

 change it to 4x3 using resize 
 [[57 75 81]
 [75 82 79]
 [68 55 69]
 [98 79 96]]


In [90]:
#Given a 5x5 matrix, extract:
 #  - The third column
  # - The last two rows
arr2d=np.random.randint(50,99,(5,5))
print(' 5x5 matrix is :\n',arr2d)
print("Accessing third column \n",arr2d[:,2])
print("Accessing The last two rows \n",arr2d[:-2])

 5x5 matrix is :
 [[91 96 67 63 87]
 [52 68 51 67 50]
 [50 95 96 63 77]
 [91 84 71 61 72]
 [83 57 78 91 75]]
Accessing third column 
 [67 51 96 71 78]
Accessing The last two rows 
 [[91 96 67 63 87]
 [52 68 51 67 50]
 [50 95 96 63 77]]


In [97]:
#5. Create an array a = np.array([10, 20, 30, 40, 50]). Extract elements at positions [1, 4, 2] using advanced indexing.
a = np.array([10, 20, 30, 40, 50])
indces=[1, 4, 2]
print('Extract elements at positions [1, 4, 2] is ....: ',a[indces])

Extract elements at positions [1, 4, 2] is ....:  [20 50 30]


In [101]:
#Create a 2D array of shape (6,6) and slice the elements from rows 2 to 5 and columns 1 to 4.
arr2d=np.random.randint(50,99,(6,6))
print(' 6x6 matrix is :\n',arr2d)
print("slicing the elements from rows 2 to 5 and columns 1 to 4\n",arr2d[2:5,1:4])


 6x6 matrix is :
 [[84 72 53 56 54 75]
 [57 53 59 76 96 84]
 [91 90 91 63 79 96]
 [98 87 74 55 54 57]
 [57 53 77 85 83 69]
 [81 61 54 73 93 71]]
slicing the elements from rows 2 to 5 and columns 1 to 4
 [[90 91 63]
 [87 74 55]
 [53 77 85]]


In [122]:
#Generate a 3x3 array using np.random.randn and find how many values are negative.
a3=np.random.randn(3,3)
np.random.seed(15)
print(a3)
count=0
for i in a3:
    for j in i:
        if(j<0):
            count+=1
        else:
            pass
print('Negative values are ...',count)

[[-0.31232848  0.33928471 -0.15590853]
 [-0.50178967  0.23556889 -1.76360526]
 [-1.09586204 -1.08776574 -0.30517005]]
Negative values are ... 7


In [150]:
# Create a 4x4 array using np.random.rand and multiply all values by 100. Find the maximum and its position.
arr4=np.random.rand(4,4)
arr4=arr4*100
print('Array is ..\n',arr4)
maxy=np.max(arr4)
pos=np.where(arr4==maxy)

print(f'maximum element in an array is {maxy}')
print(' its position is ..:',list(zip(pos[0],pos[1])))


Array is ..
 [[93.24124648 52.60595653 63.45032298 48.56884925]
 [25.72823167 47.32899633 77.28868931 75.2703489 ]
 [25.66506548 75.58340309 36.36347065  7.2479633 ]
 [80.80203216 93.64948376  9.29584482 99.11570533]]
maximum element in an array is 99.11570533257684
 its position is ..: [(np.int64(3), np.int64(3))]


In [188]:
#Create an array of shape (3, 5) with random integers between 10 and 50 using randint. Replace all even numbers with -1.
arr2d=np.random.randint(10,50,(3,5))
print('array of shape (3, 5) :\n',arr2d)
arr2d[arr2d%2==0]=-1
print(' after replacing all even numbers with -1.\n',arr2d)

array of shape (3, 5) :
 [[45 38 21 29 34]
 [21 19 16 48 29]
 [39 49 23 30 17]]
 after replacing all even numbers with -1.
 [[45 -1 21 29 -1]
 [21 19 -1 -1 29]
 [39 49 23 -1 17]]


In [195]:
#Use np.random.choice to randomly select 5 elements from [1, 2, 3, 4, 5, 6, 7] with replacement. Count how many times 3 occurs.
cate=[1, 2, 3, 4, 5, 6, 7]
arrR=np.random.choice(cate,5)
print('array is :',arrR)
print(np.count_nonzero(arrR==3))

array is : [2 3 1 6 3]
2


In [169]:
#Create a 5x5 identity matrix using np.eye. Change the diagonal values to 5.
arri=np.eye(5)
arri[arri==1]=5
print(arri)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [187]:
#Create a 3x3 matrix filled with 7 using np.full and change its center value to 0.
arr7=np.full((3,3),7)
print('3x3 matrix filled with 7 \n',arr7)
arr7[2:2]=0
arr7[:][1,1]=0
print('changing its center value to 0\n',arr7)

3x3 matrix filled with 7 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
changing its center value to 0
 [[7 7 7]
 [7 0 7]
 [7 7 7]]


In [196]:
#. Use np.linspace to create 50 values between 1 and 10. Find the difference between each consecutive value.
arr=np.linspace(1,10,50)
print(arr)
print('difference between each consecutive value is',arr[1]-arr[0])

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
difference between each consecutive value is 0.18367346938775508


In [15]:
#Create an array using np.logspace(1, 3, 5) and round off the values to 2 decimal places.

In [210]:
#Create a 2x3 array and subtract a 1D array of shape (3,) from it. Explain the broadcasting rule applied.
arr2dd=np.full((2,3),5)
print('array2D is :\n',arr2dd)
arr1d=np.full(3,2)
print('array1D is : ',arr1d)
print('after subraction  is : \n',arr2dd-arr1d)
# here the behaviour is  the compiler applies the 1-D matrix as row subraticing each rownif 2d matrix from it 
#The 1D array is treated like a row and subtracted from each row of the 2D array.

array2D is :
 [[5 5 5]
 [5 5 5]]
array1D is :  [2 2 2]
after subraction  is : 
 [[3 3 3]
 [3 3 3]]


In [1]:
#16. Create a 3x3 array and apply the following operations element-wise: square, log, exponential, and sine
import numpy as np

arr = np.random.randint(1, 10, (3, 3))
print("Original Array:\n", arr)

print("\nsquared:\n", np.square(arr))
print("\nlog:\n", np.log(arr))
print("\nExponential:\n", np.exp(arr))
print("\nSine:\n", np.sin(arr))


Original Array:
 [[5 4 9]
 [4 2 4]
 [7 8 4]]

squared:
 [[25 16 81]
 [16  4 16]
 [49 64 16]]

log:
 [[1.60943791 1.38629436 2.19722458]
 [1.38629436 0.69314718 1.38629436]
 [1.94591015 2.07944154 1.38629436]]

Exponential:
 [[1.48413159e+02 5.45981500e+01 8.10308393e+03]
 [5.45981500e+01 7.38905610e+00 5.45981500e+01]
 [1.09663316e+03 2.98095799e+03 5.45981500e+01]]

Sine:
 [[-0.95892427 -0.7568025   0.41211849]
 [-0.7568025   0.90929743 -0.7568025 ]
 [ 0.6569866   0.98935825 -0.7568025 ]]


In [2]:
#Create a 4x4 matrix with random integers between 1 and 100. Normalize the matrix using broadcasting
arr = np.random.randint(1, 101,(4, 4))
print("Original Matrix:\n", arr)
norm = (arr - arr.min()) / (arr.max() - arr.min())
print("\nNormalized Matrix:\n", norm)

Original Matrix:
 [[90 70 17 51]
 [29 25 90 81]
 [16 78 36  6]
 [16 34 37 49]]

Normalized Matrix:
 [[1.         0.76190476 0.13095238 0.53571429]
 [0.27380952 0.22619048 1.         0.89285714]
 [0.11904762 0.85714286 0.35714286 0.        ]
 [0.11904762 0.33333333 0.36904762 0.51190476]]


In [3]:
#18. Create an array of 5 angles in degrees. Convert to radians and calculate sin and cos using np.pi.
angles_deg = np.array([0, 30, 45, 60, 90])
angles_rad = angles_deg * (np.pi / 180)

print("Angles in Degrees:\n", angles_deg)
print("\nAngles in Radians:\n", angles_rad)
print("\nSine Values:\n", np.sin(angles_rad))
print("\nCosine Values:\n", np.cos(angles_rad))

Angles in Degrees:
 [ 0 30 45 60 90]

Angles in Radians:
 [0.         0.52359878 0.78539816 1.04719755 1.57079633]

Sine Values:
 [0.         0.5        0.70710678 0.8660254  1.        ]

Cosine Values:
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [4]:
##19. Given an array with float values, convert it to integer using astype and calculate the sum before and after conversion.
arr = np.array([1.7, 2.5, 3.9, 4.1, 5.8])
print("Original Float Array:\n", arr)

sum_before = np.sum(arr)
arr_int = arr.astype(int)
sum_after = np.sum(arr_int)

print("\nSum Before Conversion:", sum_before)
print("Converted Integer Array:\n", arr_int)
print("Sum After Conversion:", sum_after)

Original Float Array:
 [1.7 2.5 3.9 4.1 5.8]

Sum Before Conversion: 18.0
Converted Integer Array:
 [1 2 3 4 5]
Sum After Conversion: 15


In [21]:
#20. Create a mixed array (strings + numbers) and convert the numeric strings to actual numbers using astype.#20. Create a mixed array (strings + numbers) and convert the numeric strings to actual numbers using astype.

In [5]:
##21. Generate a 1D array with 15 random integers from 0 to 100. Replace all values divisible by 5 with -99.
arr = np.random.randint(0, 101, 15)
print("Original Array:\n", arr)

arr[arr % 5 == 0] = -99
print("\nModified Array:\n", arr)

Original Array:
 [ 9 34 96 85 87  1 21 72 53 15 48 26 38 76 95]

Modified Array:
 [  9  34  96 -99  87   1  21  72  53 -99  48  26  38  76 -99]


In [6]:
##22. Given a 2D array, write code to set all values greater than 50 to 100.
arr = np.random.randint(1, 101, (4, 4))
print("original array:\n", arr)

arr[arr > 50] = 100
print("\nmodified array:\n", arr)


original array:
 [[ 14  83  24   4]
 [ 70  68  30  47]
 [ 88  10  63  16]
 [ 50 100  33  98]]

modified array:
 [[ 14 100  24   4]
 [100 100  30  47]
 [100  10 100  16]
 [ 50 100  33 100]]


In [7]:
#23. Create an array of 20 elements using randint(1, 100, 20). Filter out only even numbers and sort them.
arr = np.random.randint(1, 100, 20)
print("original array:", arr)

even_numbers = arr[arr % 2 == 0]
sorted_evens = np.sort(even_numbers)
print("sorted even numbers:", sorted_evens)

original array: [68 76 47 30 35 79 88 33 52 13 28 17 22 89 98 64 55 77 28 30]
sorted even numbers: [22 28 28 30 30 52 64 68 76 88 98]


In [8]:
##24. Create a 4x4 array and use np.where to replace all elements < 10 with 0 and others with 1.
arr = np.random.randint(1, 21, (4, 4))
print("original array:\n", arr)

result = np.where(arr < 10, 0, 1)
print("\nmodified array:\n", result)

original array:
 [[13 15 10 17]
 [16  9 13 18]
 [11 11 19 11]
 [ 7  4  6  6]]

modified array:
 [[1 1 1 1]
 [1 0 1 1]
 [1 1 1 1]
 [0 0 0 0]]


In [9]:
#25. Use np.where to find positions of all elements divisible by 3 in a randomly generated 5x5 matrix.

arr = np.random.randint(1, 101, (5, 5))
print("original array:\n", arr)

positions = np.where(arr % 3 == 0)
print("\npositions of elements divisible by 3:\n", list(zip(positions[0], positions[1])))



original array:
 [[ 16  36  36  49  65]
 [ 83  96  63  52  61]
 [ 54  30  32  76  12]
 [ 87  23  60 100  48]
 [ 11  59  64  46   2]]

positions of elements divisible by 3:
 [(np.int64(0), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(3), np.int64(0)), (np.int64(3), np.int64(2)), (np.int64(3), np.int64(4))]


In [10]:
##26. Create a 2D array of shape (6,4). Find:

arr = np.random.randint(1, 101, (6, 4))
print("original array:\n", arr)

mean_cols = np.mean(arr, axis=0)
std_all = np.std(arr)
median_rows = np.median(arr, axis=1)

print("\nmean of each column:", mean_cols)
print("standard deviation of entire array:", std_all)
print("median of each row:", median_rows)

original array:
 [[ 38  64 100   2]
 [ 19  12  68  89]
 [ 66  51  23  34]
 [ 87  68  19  86]
 [ 31  13  47  43]
 [ 61  71  80  67]]

mean of each column: [50.33333333 46.5        56.16666667 53.5       ]
standard deviation of entire array: 27.43296754515146
median of each row: [51.  43.5 42.5 77.  37.  69. ]


In [11]:
#27. Generate a random array of 1000 values using randn. Count how many values fall between -1 and 1 (hint: normal distribution rule).
arr = np.random.randn(1000)
print("generated array:\n", arr)

count = np.sum((arr > -1) & (arr < 1))
print("\nnumber of values between -1 and 1:", count)

generated array:
 [ 1.74830710e-01  1.53070544e+00  1.09889589e+00 -1.06846681e+00
  1.12654661e+00  2.77249279e-01  6.73150120e-01  1.12260149e-01
  1.99078832e+00 -1.14877092e+00 -1.14072372e-01  4.36284846e-01
  1.94929374e+00  1.85473451e+00 -1.02099715e+00  1.13223737e+00
  1.34678564e+00 -2.25416510e-01  1.42116214e+00 -1.48068403e+00
  1.02209989e+00 -8.08110103e-01  2.28730967e-01 -9.78807421e-01
 -3.66082173e-01 -7.33482693e-01  3.05785356e-01  8.85520517e-01
 -1.56023835e+00  2.12430214e-01 -3.64483659e-01 -8.25962272e-01
  1.03616340e+00  1.39293944e+00  1.06985382e+00  1.01617843e+00
 -1.24044648e+00  1.00533483e+00 -7.85603823e-01 -6.67616681e-02
  1.20355905e+00  1.21518075e-01  2.24242217e+00 -1.44730784e-01
  2.05451574e+00  1.26902884e+00  1.03032471e+00 -1.87346306e+00
  9.07292111e-01 -1.42548504e+00  2.20514459e+00  5.53245316e-01
  6.51983876e-01  3.65188149e-01  1.18702529e-01 -9.81371930e-01
 -3.54190553e-02  4.16791658e-01 -1.29743570e+00 -8.63237479e-01
  1.839

In [12]:
#28. Create a 5x5 array and calculate row-wise and column-wise sum and mean.

arr1 = np.random.randint(1, 99, (5, 5))
print("array is:\n", arr1)
row_sum = np.sum(arr1, axis=1)
row_mean = np.mean(arr1, axis=1)
col_sum = np.sum(arr1, axis=0)
col_mean = np.mean(arr1, axis=0)
print("\nrow-wise sum:", row_sum)
print("row-wise mean:", row_mean)
print("\ncolumn-wise sum:", col_sum)
print("column-wise mean:", col_mean)


array is:
 [[84 73 74 25 11]
 [81 73 11  9 65]
 [39 54 64  1 68]
 [80 64 25 50 43]
 [ 4 76 91 55 91]]

row-wise sum: [267 239 226 262 317]
row-wise mean: [53.4 47.8 45.2 52.4 63.4]

column-wise sum: [288 340 265 140 278]
column-wise mean: [57.6 68.  53.  28.  55.6]


In [33]:
#

In [34]:
#