# NumPy Theory

## Describe the features of numpy.

- **N-Dimensional Array Object (`ndarray`)**
   * Supports multi-dimensional arrays with homogeneous data types.
   * More efficient than Python lists for large data.

- **High Performance**
  - Written in C for speed.
  - Supports fast, vectorized operations (no need for explicit loops).

- **Broadcasting**
  - Allows operations on arrays of different shapes and sizes without extra code.

- **Mathematical Functions**
  - Built-in support for math and stats functions like:
    - `sum()`, `mean()`, `std()`, `dot()`, `exp()`, `log()`, etc.

- **Random Number Generation**
  - Tools for random sampling, shuffling, and generating distributions using `numpy.random`.

- **Shape Manipulation**
  - Easily reshape, flatten, or transpose arrays:
    - `.reshape()`, `.flatten()`, `.transpose()`

- **Integration with Other Libraries**
  - Works well with popular libraries:
    - `pandas`, `matplotlib`, `scikit-learn`, `TensorFlow`, `OpenCV`, etc.

- **Linear Algebra Tools**
  - Functions for matrix operations:
    - Inverse, determinant, eigenvalues via `numpy.linalg`.

- **Handling Missing Data**
  - Supports `NaN` and masked arrays to manage missing or invalid values.

- **Memory Efficiency**
  - Uses contiguous memory blocks.
  - Consumes less memory and accesses data faster than native Python structures.


### Write the applications of numpy.
* Ideal for solving large-scale mathematical problems
* Used for handling and processing large datasets.
* Financial and Statistical Analysis
* Essential for working with input features, weight matrices, and datasets.
* Supports efficient vectorized operations used in ML libraries like TensorFlow and scikit-learn.

## How numpy is different from python sequences.
1. **Performance & Efficiency**  
   - NumPy Arrays: Faster due to C backend and contiguous memory.  
   - Python Lists: Slower due to dynamic typing and interpreter overhead.  

2. **Data Homogeneity**  
   - NumPy Arrays: Store elements of the **same type** (homogeneous).  
   - Python Lists: Can store **mixed types** (heterogeneous).  

3. **Size Mutability**  
   - NumPy Arrays: **Fixed size** (resizing creates a new array).  
   - Python Lists: **Dynamic size** (can grow/shrink with `append()`, `pop()`).  


4. **Multidimensional Support**  
   - NumPy Arrays: Native **n-dimensional arrays** (e.g., matrices).  
   - Python Lists: Need nested lists (less efficient for math ops).  
  

5. **Memory Usage**  
   - NumPy Arrays: **Memory-efficient** (compact storage).  
   - Python Lists: Higher memory overhead (stores extra metadata).  



In [67]:
#Create two 1-D arrays with numbers and strings respectively.
import numpy as np
arr1d=np.array([10,52,96,89,63,45,62,74,15,74,12,63])
arrstr=np.array([10,52,96,'89',63,45,62])
print('number array :',arr1d)
print('string array :',arrstr)

number array : [10 52 96 89 63 45 62 74 15 74 12 63]
string array : ['10' '52' '96' '89' '63' '45' '62']


In [70]:
#Create 2-D and 3-D arrays. And check their shape and dimensions using (shape and ndim methods).
arr2d=arr1d.reshape(3,4)
print(f'2d array is \n{arr2d} \n and shape {arr2d.shape} and \n dimentions is {arr2d.ndim}')
arr3d=arr1d.reshape(2,2,3)
print(f'2d array is \n\n{arr3d} \n and shape {arr3d.shape} and \n dimentions is {arr3d.ndim}')

2d array is 
[[10 52 96 89]
 [63 45 62 74]
 [15 74 12 63]] 
 and shape (3, 4) and 
 dimentions is 2
2d array is 

[[[10 52 96]
  [89 63 45]]

 [[62 74 15]
  [74 12 63]]] 
 and shape (2, 2, 3) and 
 dimentions is 3


### Explain Data Analysis in your own words using a markdown cell.
* `Data analysis` is the process of working with data to find useful information and make better decisions. Imagine you have a pile of numbers, sales records, or survey responses—data analysis helps you clean up this information, spot patterns (like which products sell best or when traffic peaks), and answer important questions. For example, a store might analyze sales data to see that most customers shop on weekends, so they could schedule more staff during those days. Tools like Excel, Python (with Pandas), or SQL help organize and study the data, while charts and graphs make trends easy to understand. In short, it turns raw data into clear insights that drive smarter actions.

# Creation of NumPy Arrays with Different Methods

In [73]:
#Create a 1D NumPy array with elements from 1 to 10 using arange().
arra1=np.arange(1,11)
print(arra1)

[ 1  2  3  4  5  6  7  8  9 10]


In [79]:
#Create a 2D array of size 3x3 filled with zeros using zeros().
arrz=np.zeros((3,3))
print(arrz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [82]:
#Create an array [5, 10, 15, 20, 25]. Find its size, item size, and total bytes used by the array.
arr=np.array([5, 10, 15, 20, 25])
print(f' array is \n{arr} \n and size  {arr.size} and \n nbytes is {arr.nbytes}')

 array is 
[ 5 10 15 20 25] 
 and size  5 and 
 nbytes is 40


In [90]:
#Use linspace() to generate an array of 7 equally spaced numbers between 0 and 14.
arr7=np.linspace(0,14,7)
print(arr7)

[ 0.          2.33333333  4.66666667  7.          9.33333333 11.66666667
 14.        ]


In [94]:
#Create a 4x4 identity matrix using eye().
arri=np.eye(4)
print(arri)
arri=np.eye(4,k=-1)
print('\n',arri)
arri=np.eye(4,k=1)
print('\n',arri)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [96]:
#Create a 3x3 diagonal matrix with the diagonal values [1, 2, 3] using diag().
arrd=np.diag([1, 2, 3])
arrd

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [98]:
#Create a 2x3 array filled with the value 9 using full()
arrf=np.full((2,3),9)
print(arrf)

[[9 9 9]
 [9 9 9]]


In [100]:
#Generate a 3x3 array of random numbers between 0 and 1 using random.rand().
import random
arrr3=np.random.rand(3,3)
print(arrr3)

[[0.28180927 0.44584523 0.4041809 ]
 [0.17663088 0.52865086 0.46002185]
 [0.35589163 0.62340036 0.80065708]]


In [120]:
#Create a 4x4 array of random integers between 10 and 50 using random.randint().
arr4d=np.random.randint(10,50,(4,4))
print(arr4d)

[[12 30 23 15]
 [39 15 14 38]
 [21 41 41 38]
 [25 42 28 49]]


In [130]:
#Generate a 1D array of 5 random numbers from a normal distribution using random.randn().
arrnrml=np.random.randn(5)
print(arrnrml)

[ 0.99043718  1.87177471 -0.34000276  0.91628248  1.10097976]


In [132]:
#Generate a 2D array of shape (2, 4) with random values uniformly distributed between -5 and 5 using random.uniform().
arrflr=np.random.uniform(-5,5,(2,4))
print(arrflr)

[[ 1.39354307 -2.00254913  3.49024794 -3.09134569]
 [-1.70180949 -3.34003004 -1.71360032  1.83175866]]


In [138]:
#Create a 1D array [10, 20, 30, 40, 50]. Access the third element and update it to 35.
arr=np.array([10, 20, 30, 40, 50])
print('Before Updating :',arr)
arr[2]=35
print('After Updating :',arr)

Before Updating : [10 20 30 40 50]
After Updating : [10 20 35 40 50]


In [146]:
#Create a 2D array of shape (3, 4) with values from 1 to 12. Slice and extract the second row.
arr2d=np.random.randint(1,12,(3,4))
print(arr2d)
print("second row is :",arr2d[1])

[[ 1  8  2  1]
 [11  6  9  3]
 [ 5 11  5  4]]
second row is : [11  6  9  3]


In [147]:
#From the same array, extract all elements in the last column.
print("all elements in the last column :",arr2d[:,3])

all elements in the last column : [1 3 4]


In [148]:
##Create a 3x3 array of ones using ones() and change its dtype to int.
arron=np.ones((3,3),dtype=np.int8)
print(arron)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [149]:
#Create an array [1, 2, 3, 4, 5] and multiply each element by 2.
arrm=np.array([1, 2, 3, 4, 5])
print(arrm*2)

[ 2  4  6  8 10]


# NumPy Methods

In [154]:
#Create a 1D NumPy array with values from 1 to 10. Access the elements at indices 2, 5, and 7.
arr1d=np.arange(1,11)
print(arr1d)
print(arr1d[2])
print(arr1d[5])
print(arr1d[7])

[ 1  2  3  4  5  6  7  8  9 10]
3
6
8


In [156]:
#Given an array `arr = np.array([10, 20, 30, 40, 50, 60, 70])`, extract a slice that contains the elements from index 2 to 5.
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[2:5])

[30 40 50]


In [168]:
#create an array of 10 random integers between 1 and 20. Extract all elements greater than 10.
arr=np.random.randint(1,20,10)
print(arr,'\nelements greater than 10 is :')
for every in arr:
    if(every>10):
        print(every,end=',')

[12  4 12  8  2  6 10 17  8 17] 
elements greater than 10 is :
12,12,17,17,

In [192]:
#Create a NumPy array of size 6. 
#Replace the second element with 99. 
#Update a slice of elements from index 2 to 4 with 0. Set the last three elements to 10.
arr6=np.random.randint(1,20,6)
np.random.seed(45)
print('Create a NumPy array of size 6 : \t\t \t:',arr6)
arr6[1]=99
print('after Replace the second element with 99. \t\t:',arr6)
arr6[2:4]=0
print('Update a slice of elements from index 2 to 4 with 0 \t:',arr6)
arr6[-3:]=10
print('Set the last three elements to 10.\t\t \t:',arr6)

Create a NumPy array of size 6 : 		 	: [12  4  1  4  5 16]
after Replace the second element with 99. 		: [12 99  1  4  5 16]
Update a slice of elements from index 2 to 4 with 0 	: [12 99  0  0  5 16]
Set the last three elements to 10.		 	: [12 99  0 10 10 10]


In [200]:
# Create a 3x3 NumPy array with values from 1 to 9. Replace the second row with all 5s. Update the third column with values [8, 9, 10].
arr39=np.arange(1,10).reshape(3,3)
print(arr39)
arr39[2]=5
print('after replacing second row with 5 \n',arr39)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
after replacing second row with 5 
 [[1 2 3]
 [4 5 6]
 [5 5 5]]


In [206]:
# Create a NumPy array with random numbers from 1 to 20. Set all values greater than 10 to zero.
arr=np.random.randint(1,20,10)
print(arr)
for i in range(arr.size):
    if(arr[i]>10):
        arr[i]=0
    else:
        pass
print('after Set all values greater than 10 to zero.:\n',arr)
 

[ 5  5 16 18  7 13 11 12  9  9]
after Set all values greater than 10 to zero.:
 [5 5 0 0 7 0 0 0 9 9]


In [207]:
#Create an array [10, 20, 30, 40] and insert 25 at index 2.
arr=np.array([10, 20, 30, 40])
arr[2]=25
print(arr)

[10 20 25 40]


In [210]:
#Create an array [1, 2, 3] and append [4, 5, 6] to it.
arr1=np.array([1, 2, 3])
arr2=np.array([4, 5, 6])
res=np.append(arr1,arr2)
print(res)



[1 2 3 4 5 6]


In [214]:
#Create an array [5, 10, 15, 20, 25] and delete the third element.
arr1=np.array([5, 10, 15, 20, 25])
res=np.delete(arr1,2)
print(res)

[ 5 10 20 25]


In [216]:
#Create an array from 1 to 12 and reshape it into a 3×4 matrix.
arr1=np.arange(1,13).reshape(3,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [223]:
#Create a 2D array and flatten it using np.ravel() and .flatten().
arr1=np.random.randint(10,150,(4,4))
print(arr1)
print('ravel',np.ravel(arr1)) # ravel doesnot modifies original arrauy
print('flatten',arr1.flatten()) #flatten modifies original arrauy

[[102 117 119 127]
 [ 68  46 127  53]
 [ 38  74  64  31]
 [105  68 102  53]]
ravel [102 117 119 127  68  46 127  53  38  74  64  31 105  68 102  53]
flatten [102 117 119 127  68  46 127  53  38  74  64  31 105  68 102  53]


In [232]:
#Create a 3×3 matrix and find its transpose using np.transpose().
arr1=np.random.randint(10,150,(3,3))
print(" original array is :\n",arr1)
trans=np.transpose(arr1)
print("\n Transposed array \n",trans)

 original array is :
 [[ 27  46  51]
 [ 61  84  66]
 [110 115  93]]

 Transposed array 
 [[ 27  61 110]
 [ 46  84 115]
 [ 51  66  93]]


In [231]:
#Create two arrays: A = np.array([2, 4, 6]), B = np.array([1, 2, 3]). Perform element-wise addition, subtraction, multiplication, and division
A = np.array([2, 4, 6])
B = np.array([1, 2, 3])
print("Addition :",A+B)
print("subtraction :",A-B)
print("multiplication :",A*B)
print("division :",A//B)

Addition : [3 6 9]
subtraction : [1 2 3]
multiplication : [ 2  8 18]
division : [2 2 2]


In [247]:
#Create two 2×2 matrices and compute their dot product using np.dot() and @ operator.
A = np.random.randint(10,58,(3,3))
B = np.random.randint(2,9,(3,3))
res=np.dot(A,B)
print('dot product result ..\n',res)
print('@ product result ..\n',A@B)

dot product result ..
 [[195 208 398]
 [263 296 506]
 [372 418 632]]
@ product result ..
 [[195 208 398]
 [263 296 506]
 [372 418 632]]


In [241]:
#create an array with values [4, 8, 15, 16, 23, 42]. Compute sum, min, max, mean, median, variance, standard deviation, and correlation coefficient.
arr=np.array([4, 8, 15, 16, 23, 42])
print('sum is :',sum(arr))
print('min is :',min(arr))
print('max is :',max(arr))
print('mean is :',np.mean(arr))
print('median is :',np.median(arr))
print('variance is :',np.var(arr))
print('standard deviation :',np.corrcoef(arr))
print('correlation coefficient. is :',np.std(arr))

sum is : 108
min is : 4
max is : 42
mean is : 18.0
median is : 15.5
variance is : 151.66666666666666
standard deviation : 1.0
correlation coefficient. is : 12.315302134607444
