# Python and NumPy Assignment - 50 Questions 

## What are the key features of Python?


1. **Simple and Readable** – Python code looks almost like plain English, so it’s easy to learn and understand, even for beginners.  

2. **Versatile** – You can use Python for web development, data analysis, AI, machine learning, automation, and much more.  

3. **Huge Community Support** – With millions of developers worldwide, you’ll always find help, tutorials, and libraries for almost anything.  

4. **Cross-Platform** – Python runs on Windows, macOS, Linux, and even small devices like Raspberry Pi without changing much code.  

5. **Rich Libraries** – From NumPy for math to Django for web apps, Python has a massive collection of ready-made modules to save time and effort.  


# Explain the difference between a list, tuple, set, and dictionary in Python.
1. **List**
   - Ordered collection of items.
   - Allows duplicates.
   - Mutable : you can change, add, or remove elements.


2. **Tuple**
   - Ordered collection like a list.
   - Allows duplicates.
   - Immutable  once created, you cannot modify it.


3. **Set**
   - Unordered collection of unique elements.
   - Does **not** allow duplicates.
   - Mutable (you can add/remove items), but elements must be immutable (e.g., numbers, strings).


4. **Dictionary**
   - Collection of **key-value pairs**.
   - Keys must be unique and immutable.
   - Very useful for fast lookups.


### What is the difference between 'is' and '==' in Python?
* == -> compares values 
* is-> compares values along with addresses

In [38]:
# Write a Python program to find the factorial of a number using recursion.
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

print(f"Factorial  is: {factorial(5)}")


Factorial  is: 120


# Explain the concept of list comprehension with an example.
**Concept:**  
List comprehension is a concise way to create lists in Python.  
Instead of writing a loop and appending items, you can build the list in a single line.

**General Syntax:**
```python
[expression for item in iterable if condition]

In [40]:
evens = [x for x in range(1, 11) if x % 2 == 0]
print(evens)

[2, 4, 6, 8, 10]


In [41]:
# Write a program to check whether a number is prime or not.
def is_prime(num):
    if num <= 1:
        return False
    
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

n = 29
if is_prime(n):
    print(f"{n} is a Prime number.")
else:
    print(f"{n} is NOT a Prime number.")


29 is a Prime number.


# What is the purpose of the 'with' statement in Python?
#### The with statement in Python is used to manage resources efficiently by automatically handling setup and cleanup (like closing files).

## Explain the use of *args and **kwargs in Python functions.


- **`*args`** allows a function to accept any number of positional arguments.  
- **`**kwargs`** allows a function to accept any number of keyword arguments.  


## What are Python lambda functions? Give an example.


#### Lambda functions are small, anonymous functions in Python defined with the `lambda` keyword, used for short, one-line operations without formally declaring a function.



In [44]:
val= lambda x:x*x
val(5)

25

In [45]:
# Write a Python program to reverse a string
def rev_str(s):
    return s[::-1]

txt = "HelloWorld"
print(rev_str(txt))


dlroWolleH


# What are Python generators? How are they different from iterators?

- **Generators** are special functions that use the `yield` keyword to produce values one at a time, creating an iterator automatically.  
- **Iterators** are objects with `__iter__()` and `__next__()` methods that allow iteration over elements.  
- **Difference:** Generators simplify writing iterators, use less memory (lazy evaluation), and are written like functions, while iterators are manually implemented classes/objects.  


# Explain exception handling in Python with try-except-finally blocks.
- **try** → The block of code to test for errors.  
- **except** → The block of code that runs if an error occurs.  
- **finally** → The block of code that always runs, whether an error occurs or not.  

# What are the different data types available in Python?
1. *Numeric Types** → int, float, complex  
2. **Sequence Types** → list, tuple, range, string (str)  
3. **Set Types** → set, 
4. **Mapping Type** → dict  
5. **Boolean Type** → bool  

In [49]:
# Write a program to count the frequency of each word in a given string.
text = "hello chiiddu how are you"
dict1 = {}

for word in text.split():
    dict1[word] = freq.get(word, 0) + 1

print(dict1)

{'hello': 2, 'chiiddu': 2, 'how': 2, 'are': 2, 'you': 2}


## What is the difference between shallow copy and deep copy in Python?


- **Shallow Copy** → Copies only references (one level).  
- **Deep Copy** → Copies everything recursively (all levels).  


# What is NumPy and why is it used?
*NumPy** (Numerical Python) is a powerful library for numerical computing.  
It is mainly used for:

- Handling large multi-dimensional arrays and matrices.  
- Performing fast mathematical and statistical operations.  

## How is a NumPy array different from a Python list?
*Storage** → NumPy arrays are stored more compactly and use less memory, while lists are larger.  
2. **Performance** → NumPy arrays are much faster for numerical operations compared to lists.  
3. **Data Type** → NumPy arrays hold elements of the same type, whereas lists can store mixed data types.  
4. **Operations** → NumPy arrays support vectorized operations (element-wise math), but lists require loops.  
5. **Functionality** → NumPy provides advanced mathematical functions, slicing, and broadcasting, which lists do not.  

### What are the advantages of using NumPy arrays?
- NumPy arrays are faster and more memory-efficient than Python lists, support vectorized operations without loops, provide advanced mathematical functions for tasks like linear algebra and statistics, and integrate seamlessly with popular data science libraries such as Pandas, SciPy, and TensorFlow.  

In [55]:
# Write the syntax for creating a NumPy array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [56]:
# What is the shape and dtype of an array?
arr.shape

(6,)

In [57]:
arr.dtype

dtype('int64')

### Explain the use of np.zeros(), np.ones(), and np.full().
*np.zeros(shape)** → Creates an array filled with zeros.  
- **np.ones(shape)** → Creates an array filled with ones.  
- **np.full(shape, value)** → Creates an array filled with a specified value.  


### How do you generate random numbers using NumPy?
- **np.random.rand(n)** → Generates random numbers between 0 and 1.  
- **np.random.randint(low, high, size)** → Generates random integers in a given range.  
- **np.random.randn(n)** → Generates random numbers from a normal distribution.  
- **np.random.random(size)** → Generates random floats between 0 and 1.  

### What is broadcasting in NumPy? Give an example
**Broadcasting** is the ability of NumPy to perform arithmetic operations on arrays of different shapes by automatically expanding the smaller array to match the larger one.  

In [58]:
# How do you reshape a NumPy array?
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

## Explain the difference between reshape() and resize().
- **reshape()** → Returns a new array with the specified shape without modifying the original array (unless `inplace`).  
- **resize()** → Modifies the original array itself and can change its size (adding zeros if needed).  

# What is the use of np.linspace() and np.logspace()?
- **np.linspace(start, stop, num)** → Returns `num` evenly spaced values between `start` and `stop`.  
- **np.logspace(start, stop, num, base=10)** → Returns `num` values spaced evenly on a log scale, from `base**start` to `base**stop`.  

In [59]:
# Write the syntax to perform element-wise addition and multiplication on arrays.
arr+5

array([ 6,  7,  8,  9, 10, 11])

In [60]:
arr*2

array([ 2,  4,  6,  8, 10, 12])

# Explain slicing and indexing in NumPy for 2D arrays.
1. **Indexing** → Access elements using row and column indices.  
   Example: `arr[1, 2]` → element at 2nd row, 3rd column.  

2. **Slicing** → Extract sub-arrays using ranges.  
   Example: `arr[0:2, 1:3]` → rows 0–1 and columns 1–2.  

In [64]:
# How do you perform type conversion in NumPy arrays?
arr=arr.astype(str)
arr

array(['1', '2', '3', '4', '5', '6'], dtype='<U21')

## What are the different statistical functions in NumPy?
1. **np.mean()** → Calculates the average value.  
2. **np.median()** → Finds the middle value.  
3. **np.std()** → Computes the standard deviation.  
4. **np.var()** → Computes the variance.  
5. **np.min() / np.max()** → Finds minimum and maximum values.  
6. **np.percentile()** → Calculates the percentile of data.  
7. **np.sum()** → Returns the sum of elements.  

In [67]:
#Write a NumPy program to create an array of 10 zeros and change the fifth value to 1.
arr10=np.zeros(10)
arr10[4]=1
arr10

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [69]:
#Write a NumPy program to reverse an array (first element becomes last).
arr[::-1]

array(['6', '5', '4', '3', '2', '1'], dtype='<U21')

In [73]:
#How can you find unique elements in a NumPy array?
arr2=np.array([5,5,1,2,6,6,5])
np.unique(arr2)

array([1, 2, 5, 6])

In [76]:
#Write a Python program to read a CSV file using NumPy.
data = np.genfromtxt(r"C:\Users\chidv\Downloads\Data_sets\TelecomCustomerChurn.csv", delimiter=",")

print(data)

[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan 0.0000e+00 ... 2.9850e+01 2.9850e+01        nan]
 [       nan        nan 0.0000e+00 ... 5.6950e+01 1.8895e+03        nan]
 ...
 [       nan        nan 0.0000e+00 ... 2.9600e+01 3.4645e+02        nan]
 [       nan        nan 1.0000e+00 ... 7.4400e+01 3.0660e+02        nan]
 [       nan        nan 0.0000e+00 ... 1.0565e+02 6.8445e+03        nan]]


### What is the difference between np.array_split and np.split?
- **np.split(array, sections)** → Splits an array into equal parts; raises an error if it cannot be divided equally.  
- **np.array_split(array, sections)** → Splits an array into parts as equal as possible; works even if the array size isn’t perfectly divisible.  

In [82]:
##Write a Python program to calculate the dot product of two vectors.
arr1=np.array([2,2,3,1,2,5,3])
arr2=np.array([5,5,1,2,6,6,5])
np.dot(arr1,arr2)

np.int64(82)

In [95]:
#How do you sort a NumPy array by a specific column?
arr2=np.random.randint(12,99,9).reshape(3,3)
sorted_arr = arr2[arr2[:, 1].argsort()]
print("\nSorted by 2nd column:\n", sorted_arr)


Sorted by 2nd column:
 [[64 22 79]
 [87 44 32]
 [30 75 52]]


In [96]:
# Write a program to create a 3x3 identity matrix using NumPy.
arr2=np.random.randint(12,99,9).reshape(3,3)
arr2

array([[71, 87, 21],
       [78, 31, 85],
       [80, 16, 31]], dtype=int32)

In [99]:
#Write a NumPy program to generate a random 4x4 array and find the maximum and minimum values.
arr2=np.random.randint(12,99,16).reshape(4,4)
arr2

array([[94, 52, 43, 55],
       [44, 95, 15, 20],
       [16, 32, 92, 86],
       [87, 73, 46, 62]], dtype=int32)

In [100]:
print(arr2.max())
print(arr2.min())

95
15


### What is the use of np.where()? Provide an example.
- **np.where()** is used to return the indices of elements that satisfy a given condition.  
- It can also be used to select values based on a condition (like an inline if-else).


In [116]:
print(np.where(arr2==43))

(array([0]), array([2]))


In [120]:
#Write code to find the sum of diagonal elements in a matrix using NumPy.
arr2.diagonal().sum()

np.int64(343)

In [129]:
#ow do you stack two arrays vertically and horizontally?
arr=np.random.randint(1,100,9).reshape(3,3)
arr2=np.random.randint(1,100,9).reshape(3,3)
print(arr," \n\n",arr2)

[[36 64 42]
 [86 47  5]
 [70 33 55]]  

 [[22 75 32]
 [11 38  3]
 [59 65 18]]


In [130]:
np.vstack((arr,arr2))

array([[36, 64, 42],
       [86, 47,  5],
       [70, 33, 55],
       [22, 75, 32],
       [11, 38,  3],
       [59, 65, 18]], dtype=int32)

In [131]:
np.hstack((arr,arr2))

array([[36, 64, 42, 22, 75, 32],
       [86, 47,  5, 11, 38,  3],
       [70, 33, 55, 59, 65, 18]], dtype=int32)

In [136]:
#Write a program to filter out all values > 50 from an array
arr2[np.where(arr2>50)]

array([75, 59, 65], dtype=int32)

In [144]:
#How to calculate mean, median, and standard deviation of an array?

mean=arr2.mean()
median= np.median(arr2)
std=arr2.std()
print(f" mean: {mean}\n median: {median}\n std: {std}")

 mean: 35.888888888888886
 median: 32.0
 std: 23.909293611222694


### What is the use of np.ndim, np.shape, and np.size?
- **np.ndim(array)** → Returns the number of dimensions (axes) of the array.  
- **np.shape(array)** → Returns a tuple showing the size of the array in each dimension.  
- **np.size(array)** → Returns the total number of elements in the array.  

In [147]:
#How to flatten a multi-dimensional NumPy array?
arr2.flatten()

array([22, 75, 32, 11, 38,  3, 59, 65, 18], dtype=int32)

In [152]:
#Write a code to compute the cumulative sum of a NumPy array.
cumsum_arr = np.cumsum(arr2)  
print(cumsum_arr)  

[ 22  97 129 140 178 181 240 305 323]


### What is the difference between np.copy() and normal assignment?
- **Normal Assignment (`b = a`)** → Creates a reference; both `a` and `b` point to the same data.  
- **`np.copy()`** → Creates a new independent copy; modifying one does not affect the other.  

In [160]:
#Write a NumPy program to create an array of integers from 1 to 100 and reshape it to 10x10.
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [174]:
#Write a Python program to merge two NumPy arrays and remove duplicates.
a1=np.arange(1,9)
a2=np.arange(5,12)
print(f"array1 is {a1} \narray2 is {a2} \n")
x=np.concat((a1,a2))
a3 = np.unique(x)  
print(a3)

array1 is [1 2 3 4 5 6 7 8] 
array2 is [ 5  6  7  8  9 10 11] 

[ 1  2  3  4  5  6  7  8  9 10 11]
