## Numpy Random Numbers

* The np.random.rand method, generates an array with random numbers that are uniformly distributed between 0 and 1.
* The np.random.randn method, generates an array with random numbers that are normally distributed with mean = 0 and sd = 1.
* The np.random.randint method, generates an array with random numbers that are uniformly distributed between 0 and given integer.
* The np.random.uniform method, generates random float values.



## rand

In [17]:
import random 
import numpy as np
print(f" generates a random number  b/w 0,1  :  {np.random.rand() }")
print(f" \n generates a random 1-D array  b/w 0,1  :  {np.random.rand(3) }")
print(f" \n generates a random 2-D array  b/w 0,1 by given shape  :  \n\n{np.random.rand(4,4)}")
arr=np.random.rand(4,7)

 generates a random number  b/w 0,1  :  0.23092090787403186
 
 generates a random 1-D array  b/w 0,1  :  [0.93302366 0.39634695 0.86443509]
 
 generates a random 2-D array  b/w 0,1 by given shape  :  

[[0.07327274 0.51139403 0.06344766 0.29345388]
 [0.47522895 0.11893139 0.06656852 0.15960707]
 [0.01686078 0.83232341 0.76090619 0.08629114]
 [0.60843368 0.21806207 0.46907793 0.51319776]]


# randn -
* The np.random.randn method, generates an array with random numbers that are normally distributed with mean = 0 and sd = 1

In [20]:
import random 
import numpy as np
print(f" generates a random number  b/w 0,1  :  {np.random.randn() }")
print(f" \n generates a random 1-D array  b/w 0,1  :  {np.random.randn(3) }")
print(f" \n generates a random 2-D array  b/w 0,1 by given shape  :  \n\n{np.random.randn(3,4,4)}")
arr=np.random.rand(4,7)

 generates a random number  b/w 0,1  :  0.8064157572847239
 
 generates a random 1-D array  b/w 0,1  :  [0.28485978 1.10648255 1.14999438]
 
 generates a random 2-D array  b/w 0,1 by given shape  :  

[[[ 1.46838414  4.07159242  1.15384236 -0.76360465]
  [ 0.52831117 -0.90918457 -0.99186259  0.68873872]
  [ 0.42522094  2.06241527 -0.01699757  1.01126931]
  [-1.50796022 -0.78324388  0.99351282  0.62760383]]

 [[ 0.70983609  2.72939543  1.49092619 -2.11887049]
  [-1.36577857  1.57856035  0.82793775 -0.48087284]
  [ 0.02321187  0.44344417 -0.79433073  0.7328251 ]
  [ 0.77623025 -1.27014417 -0.19054687  1.36156413]]

 [[ 0.83015753 -0.69068    -0.1326826  -0.56017403]
  [ 0.38110309  1.02158548 -0.74151     1.93441566]
  [-0.59056509 -0.30360491  1.09745521  1.33806215]
  [-0.29842946 -0.7523692  -0.15756144 -0.4921089 ]]]


# random.randint
* •	The np.random.randint method, generates an array with random numbers that are uniformly distributed between 0 and given integer.

In [26]:
import random 
import numpy as np
print(f" \n generates a random number  b/w 0,1  :  {np.random.randint(5) }") # if only one number is given then min==0, max =given integer 
print(f"\n  generates a random number  b/w 0,1  :  {np.random.randint(2,5) }")
print(f" \n generates a random 1-D array  b/w 0,1  :  {np.random.randint(10,150,6) }")
print(f" \n generates a random 2-D array  b/w 0,1 by given shape  :  \n\n{np.random.randint(10,150,(4,5))}")
arr=np.random.rand(4,7)

 
 generates a random number  b/w 0,1  :  4

  generates a random number  b/w 0,1  :  3
 
 generates a random 1-D array  b/w 0,1  :  [ 72 148 130 144  21  23]
 
 generates a random 2-D array  b/w 0,1 by given shape  :  

[[112  92 148 142  47]
 [127  92 131 103  64]
 [125  90  59  36  77]
 [ 43  39  49  55 134]]


# np.random.uniform  
*  The np.random.uniform method, generates random float values.m

In [31]:
import random 
import numpy as np
print(f"\n Generates a random float number  b/w 0,1  :  {np.random.uniform(2,5) }")
print(f" \n generates a random float 1-D array  b/w 0,1  :  \n{np.random.uniform(10,150,6) }")
print(f" \n generates a random float 2-D array  b/w 0,1 by given shape  :  \n\n{np.random.uniform(10,150,(4,5))}")
arr=np.random.rand(4,7)


 Generates a random float number  b/w 0,1  :  3.2048370913458535
 
 generates a random float 1-D array  b/w 0,1  :  
[ 88.53499358 132.92016941 149.8759157   57.20767844 108.36614071
 121.98734549]
 
 generates a random float 2-D array  b/w 0,1 by given shape  :  

[[141.02087139  77.1669322   13.82447379 148.62725984  40.25941372]
 [118.05376502 121.46966829 137.99038383  53.59741831  11.68274584]
 [105.49143137  51.33764879 117.04529858  18.49901911  54.10277885]
 [117.50831223 112.9004792   93.03767849  11.38334873  43.7795294 ]]
