In [24]:
# creating the id array
import random
import numpy as np
np.random.seed(15)
arr1d=np.random.randint(15,45,8)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [25]:
# 1 . homogenous and hetrogenious behaviour in the array vs list
#basically list is ordered and shows the hetrogrogenious behovior
# that mean list allows us to define  the multiple or diffrent type of data int
# in lst=[1,'potato', True, 10.5] allows it
# but coming to the arrays that is homogenious that only allows us to define the same data type elements


In [26]:
# np.array([1,5,'8',4]
# it willl allows all elements are are converted into the string values 
import numpy as np
arr=np.array([1,5,'8',4])
print(arr) #All are converted into strings 
             

['1' '5' '8' '4']


In [27]:
#Order of priority 
# bool<int<float<str
arr1=np.array([1,5,8.2,4])
print(arr1)  #all are converted into float

[1.  5.  8.2 4. ]


In [28]:
arr1=np.array([1,5,False,4])
print(arr1)  #bool valuea are converted into int 

[1 5 0 4]


In [29]:
# bool<int<float<str
#applying order 
arr1=np.array([1,5.2,False,'4'])
print(arr1)  #all values converted into str bcox higher order


['1' '5.2' 'False' '4']


In [30]:
#2. Arrays are desined t perform the arthematic operations
# majory we use arrays for 

arr1=np.array([7,4,8,6,10,9,5])
print(arr1**2 )     # we can easyly perform arthemic operations 


[ 49  16  64  36 100  81  25]


In [31]:
#but in the list we cannot perform the operations like this directlt
lst=[7,4,8,6,10,9,5] 
print(lst**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
#if y
arr1=np.array([7,4,8,6,'10',9,5]) #all are converted into strings
print(arr1**2 )


# Reshaping an array

In [ ]:
arr1=np.array([[10,2,0],[4,5,5]])
print(arr1,arr1.shape)
print(arr1.size ," is size")

In [ ]:
print(arr1.reshape(2,3,1))

In [ ]:
arr1     #original array remains the same 

In [ ]:
arr=np.array(range(1,9))
print(arr,arr.shape)
print(arr.size ," is size")

# reshaping them into 2d arrays 

In [ ]:
#1,2,4,8 are the factorials

In [ ]:
#sooooooooo
# possible reshapes iRe

print(arr.reshape(2,4),f'\n {'--'*30}')
print(arr.reshape(4,2),f'\n {'--'*30}')
print(arr.reshape(8,1),f'\n {'--'*30}')
print(arr.reshape(1,8),f'\n {'--'*30}')

# reshaping them into 3d arrays 

In [ ]:
#sooooooooo
# some of possible reshapes iRe
#1,2,4,8 are the factorials
print(arr.reshape(2,2,2),f'\n {'--'*30}')
print(arr.reshape(2,4,1),f'\n {'--'*30}')
print(arr.reshape(4,2,1),f'\n {'--'*30}')
print(arr.reshape(1,8,1),f'\n {'--'*30}')


# # reshaping them into 4d arrays 

In [ ]:
#1,2,4,8 are the factorials
#coming  to the 4d arrays it will read the arrays as 
#reshape(1,2,20,3) 
# it can be reades as given 4d array has one 3d array that contain two (20,3) shaped 2-d arrays

arr4=np.array(range(1,121))
print(arr4.shape,f' is the shape\n {'--'*30}')
# some factorials of 120 are 1,4,20,40,30 etc 
print(arr4.reshape(1,2,20,3),f' is the shape\n {'--'*30}')

# `reshape(1,-1)` & `reshape(-1,1)`

In [ ]:
#reshape(1,-1) & reshape(-1,1) are the simple funtions 
# used to determing the varible length shape mean varible sized colums and rows'
#reshape(1,-1) :: that mean if you defined that will convert given array into 2d having 1 row and len(Array) colums
#reshape(1,-1) :: that mean if you defined that will convert given array into 2d having len(Array) rows and 1 colum
arrn=np.array(range(1,11)) # size is 10
print('given array is :',arrn)
print('given array size is :',arrn.size)
#reshaping by varible length shape 
print(arrn.reshape(1,-1),"---> # converted into 2-D array with 1row and n colums ")
print(arrn.reshape(-1,1),"---> # converted into 2-D array with n rows and 1 colums  ")

In [ ]:
#Data Types Supported by NumPy
import numpy as np
# basically python supports the wide range of the data types
# setteing the custum data type it will save the memory
import random as rd

In [ ]:
arr1=np.array(range(1,121)).reshape(2,5,12)
print(arr1,'\n \n size is :',arr1.size,f"\n dtype is :{arr1.dtype}") # dtype is assigned to int8

In [ ]:
print(arr2d,'\n \n memory is :',arr2d.nbytes,f"\n dtype is :{arr2d.dtype}") # dtype is assigned by the computer

In [ ]:
# creating with int8
arr2d=np.array(range(1,121),dtype=np.int8).reshape(2,5,12)
print(arr2d,'\n \n memory allocted is :',arr2d.nbytes,f"\n dtype is :{arr2d.dtype}") # dtype is assigned to int8
print('--'*30)

In [ ]:

# creating with uint8
arr2d=np.array(range(1,121),dtype=np.uint8).reshape(2,5,12)
print(arr2d,'\n \n memory allocted is :',arr2d.nbytes,f"\n dtype is :{arr2d.dtype}") # dtype is assigned to int8
print('--'*30)

In [ ]:
arr2d = np.array(range(1,41), dtype = np.uint8).reshape(5,8)
print(arr2d)
print(arr2d.dtype, arr2d.nbytes)
print("--"*30)
arr2d = np.array(range(1,41), dtype = np.int64).reshape(5,8)
print(arr2d)
print(arr2d.dtype, arr2d.nbytes)
print("--"*30)
arr2d = np.array(range(1,41), dtype = int).reshape(5,8)
print(arr2d)
print(arr2d.dtype, arr2d.nbytes)
print("--"*30)
arr2d = np.array(range(1,41), dtype = np.float64).reshape(5,8)
print(arr2d)
print(arr2d.dtype, arr2d.nbytes)
print("--"*30)

## HOW arrays vary size in strings 

In [ ]:
arr1=np.array(['chiddu','chidvilas','kumkapalla'])

In [ ]:
print(arr1)
print(arr1.dtype, arr1.nbytes)
print("--"*30)        #<U10 meens all strings length is less than = 10
# for example if i give more lengths
arr2=np.array(['chiddu','chidvilas','kumkapalla','tiruvanantapuramcity'])
print(arr2)
print(arr2.dtype, arr2.nbytes) #U<20 and size also increased 
print("--"*30)        

In [ ]:
#if i tries to assign the values with the more chareters to smaller dtype
arr3=np.array(['chiddu','chidvilas','kumkapalla','tiruvanantapuramcity'],dtype='U10')

print(arr3,f"\n data type is :{arr3.dtype}", f"\n memory size is :{arr3.nbytes}") # ONLY PRINTS 10 CHARETERS
print("--"*30)  
arr3=np.array(['chiddu','chidvilas','kumkapalla','tiruvanantapuramcity'],dtype='U5')
print(arr3,f"\n data type is :{arr3.dtype}", f"\n memory size is :{arr3.nbytes}")  # ONLY PRINTS 5 CHARETERS
print("--"*30)    
arr3=np.array(['chiddu','chidvilas','kumkapalla','tiruvanantapuramcity'],dtype='U2')
print(arr3,f"\n data type is :{arr3.dtype}", f"\n memory size is :{arr3.nbytes}")  # ONLY PRINTS 2 CHARETERS
print("--"*30)    

## Down Casting

- converting the data from larsger dtype to smaller is known as the downcasting
- involes the loss of data

In [ ]:
arr1=np.random.rand(10)
arr1

In [ ]:
arr1.size
arr1.nbytes

In [ ]:
#down casting upper dtype to lower 
#float to int
arr1=arr1.astype(np.int32)   #leads to loose of data
arr1

In [ ]:
arr1.size
arr1.nbytes

# More Array operations

In [ ]:
# Transpose
arr2d=np.random.randint(9,89,(5,5))
arr2d

In [ ]:
arr2d.T

In [ ]:
np.transpose(arr2d)

## Flatten and Ravel

`flatten():`

Always returns a copy of the original array. This means a new, independent array is created in memory, and any modifications made to the flattened array will not affect the original array.

`ravel():`

Returns a view of the original array whenever possible. A view is essentially a reference to the original data, meaning they share the same memory.

In [ ]:
flattened=arr2d.flatten()
raveled=arr2d.ravel()

In [ ]:
flattened 
arr2d

In [ ]:
raveled
arr2d

## If any change is happened to flattened array it doesnot changes org array bcoz it returns a copy ,but in the Ravel array it will modifies the original array


In [ ]:
flattened[0]=999
arr2d #oroginal array remains unchaged

In [ ]:
raveled[0]=999
arr2d

## fliping the arrays

In [ ]:
print(arr2d)

In [ ]:
np.flip(arr2d) #combination and horizontal and vertical flip

In [ ]:
np.flip(arr2d,axis=0)  #vertical flip controls rows
np.flipud(arr2d)           #or up down flip

In [ ]:
np.flip(arr2d,axis=1)  #horizontal flip conrols column
np.fliplr(arr2d)         #or left right flip

In [ ]:
arr2d

## rotation in arrays 

In [ ]:

np.rot90(arr2d) #90 degrees anti-clock wise
np.rot90(np.rot90(arr2d)) #180 degrees anti-clock wise
np.rot90(np.rot90(np.rot90(arr2d))) # 270 degrees anti-clock wise
np.rot90(np.rot90(np.rot90(np.rot90(arr2d)))) # 360 degrees anti-clock wise

## Boolean Indexing

In [ ]:
arr2d

In [ ]:
arr2d[arr2d%2==0]

In [ ]:
arr2d[(arr2d+1==52)]

In [ ]:
arr2d[(arr2d%2==0)&(arr2d%4==0)]

In [ ]:
odd=arr2d%3==0
arr2d[odd]

In [ ]:
arr2d%3

## updating values by the bOOl indexing

In [ ]:
arr2d

In [ ]:
arr2d[arr2d==999]=25

In [ ]:
arr2d # so we updated the vlues using the array indexing

In [ ]:
arr2d[(arr2d%2==0) & (arr2d%4==0) & (arr2d%77==0)]

(arr2d%2==0) & (arr2d%4==0) & (arr2d%77==0)

## TASK: get the list of numbers greater than 150 from the below array 

In [223]:
np.random.seed(123) 

_1darray = np.random.randint(25,255,25) 
_1darray

array([134, 151,  91, 245, 123,  42, 108, 131, 148,  82, 239, 250, 121,
       138, 151,  72,  98,  57, 199, 249, 136, 178, 108, 103, 189],
      dtype=int32)

In [ ]:

mty=[]
for every in _1darray:
    if(every>150):
        mty.append(int(every))
print(mty)
    
#mannual method

In [ ]:
# bool indexing
_1darray[_1darray>150]

In [ ]:
# Get the numbers that are divisible by 2
# Replace or assign new values 

for i in range(len(_1darray)):
     if(_1darray[i]%2==0):
        _1darray[i]=np.random.randint(5,10)

_1darray

In [ ]:
np.random.seed(123) 

_1darray = np.random.randint(25,255,25) 
_1darray
# Get the numbers that are divisible by 2
# Replace or assign new values 
_1darray[_1darray%2==0]=np.random.randint(5,10)
_1darray

# NumPy `where()`, `any()` and `all()`

- np.where() → returns indices (or values) where a condition is true.

- np.any() → returns True if at least one condition is true.

- np.all() → returns True only if all conditions are true.

In [224]:
_1darray

array([134, 151,  91, 245, 123,  42, 108, 131, 148,  82, 239, 250, 121,
       138, 151,  72,  98,  57, 199, 249, 136, 178, 108, 103, 189],
      dtype=int32)

In [230]:
np.where(_1darray>150) #indexes where condition is true 

(array([ 1,  3, 10, 11, 14, 18, 19, 21, 24]),)

In [232]:
np.all(_1darray>150) #tue true if the condition satisfies to every element in array
np.all(_1darray>0)

np.False_

np.True_

In [234]:
np.any(_1darray>250) # returns true when sny element satisfies the condition
np.any(_1darray>150)

np.False_

np.True_

## Arithmetic operations on Arrays

In [ ]:
# +,-,*,/ etc


In [36]:
arr1=np.random.randint(1,9,(2,2))
arr2=np.ones((2,2))

In [37]:
arr1
arr2

array([[8, 4],
       [6, 7]], dtype=int32)

array([[1., 1.],
       [1., 1.]])

In [38]:
arr1+arr2

array([[9., 5.],
       [7., 8.]])

In [39]:
arr1-arr2

array([[7., 3.],
       [5., 6.]])

In [40]:
arr2-arr1

array([[-7., -3.],
       [-5., -6.]])

In [41]:
arr1*arr2

array([[8., 4.],
       [6., 7.]])

In [42]:
arr1//arr2

array([[8., 4.],
       [6., 7.]])

In [43]:
arr2+18

array([[19., 19.],
       [19., 19.]])

In [44]:
arr2-1

array([[0., 0.],
       [0., 0.]])

In [46]:
arr1**2

array([[64, 16],
       [36, 49]], dtype=int32)

# Arthemetic Funtions

In [48]:
arr1
arr2

array([[8, 4],
       [6, 7]], dtype=int32)

array([[1., 1.],
       [1., 1.]])

In [51]:
np.add(arr1,arr2)
np.subtract(arr1,arr2)
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
np.mod(arr1,arr2)
np.power(arr1,arr2)

array([[9., 5.],
       [7., 8.]])

array([[7., 3.],
       [5., 6.]])

array([[8., 4.],
       [6., 7.]])

array([[8., 4.],
       [6., 7.]])

array([[0., 0.],
       [0., 0.]])

array([[8., 4.],
       [6., 7.]])

# Matrix Multiplication

In [52]:
# matrix mutiplition or Dot product
arr1.dot(arr2)

array([[12., 12.],
       [13., 13.]])

In [65]:
arr1=np.ones((3,3))
arr2=np.full((3,3),5)

In [66]:
arr1
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [67]:
arr1.dot(arr2)

array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

In [68]:
np.dot(arr1,arr2)

array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

In [71]:
mul=arr1@arr2 
mul

array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

# Statistical functions

In [72]:
np.mean(mul)

np.float64(15.0)

In [79]:
mul=np.random.randint(12,85,(5,5))
mul

array([[82, 53, 46, 52, 34],
       [75, 68, 40, 16, 19],
       [78, 54, 19, 36, 72],
       [57, 61, 65, 41, 45],
       [14, 54, 63, 74, 35]], dtype=int32)

In [78]:
np.mean(mul)
np.median(mul)
np.std(mul)
np.var(mul)
np.max(mul)
np.min(mul)

np.float64(48.52)

np.float64(46.0)

np.float64(18.0889358448749)

np.float64(327.2096)

np.int32(80)

np.int32(13)

# Trigonometric Functions

In [83]:
np.sin(45)
np.cos(45)
np.tan(45)

np.float64(0.8509035245341184)

np.float64(0.5253219888177297)

np.float64(1.6197751905438615)

In [84]:
np.sin(90)
np.cos(90)
np.tan(90)

np.float64(0.8939966636005579)

np.float64(-0.4480736161291701)

np.float64(-1.995200412208242)

## Other Mathematical Funtion

In [86]:
mul

array([[82, 53, 46, 52, 34],
       [75, 68, 40, 16, 19],
       [78, 54, 19, 36, 72],
       [57, 61, 65, 41, 45],
       [14, 54, 63, 74, 35]], dtype=int32)

In [91]:
np.square(mul)
np.sqrt(mul)
np.exp(mul)
np.log(mul)

array([[6724, 2809, 2116, 2704, 1156],
       [5625, 4624, 1600,  256,  361],
       [6084, 2916,  361, 1296, 5184],
       [3249, 3721, 4225, 1681, 2025],
       [ 196, 2916, 3969, 5476, 1225]], dtype=int32)

array([[9.05538514, 7.28010989, 6.78232998, 7.21110255, 5.83095189],
       [8.66025404, 8.24621125, 6.32455532, 4.        , 4.35889894],
       [8.83176087, 7.34846923, 4.35889894, 6.        , 8.48528137],
       [7.54983444, 7.81024968, 8.06225775, 6.40312424, 6.70820393],
       [3.74165739, 7.34846923, 7.93725393, 8.60232527, 5.91607978]])

array([[4.09399696e+35, 1.04137594e+23, 9.49611942e+19, 3.83100800e+22,
        5.83461743e+14],
       [3.73324200e+32, 3.40427605e+29, 2.35385267e+17, 8.88611052e+06,
        1.78482301e+08],
       [7.49841700e+33, 2.83075330e+23, 1.78482301e+08, 4.31123155e+15,
        1.85867175e+31],
       [5.68572000e+24, 3.10429794e+26, 1.69488924e+28, 6.39843494e+17,
        3.49342711e+19],
       [1.20260428e+06, 2.83075330e+23, 2.29378316e+27, 1.37338298e+32,
        1.58601345e+15]])

array([[4.40671925, 3.97029191, 3.8286414 , 3.95124372, 3.52636052],
       [4.31748811, 4.21950771, 3.68887945, 2.77258872, 2.94443898],
       [4.35670883, 3.98898405, 2.94443898, 3.58351894, 4.27666612],
       [4.04305127, 4.11087386, 4.17438727, 3.71357207, 3.80666249],
       [2.63905733, 3.98898405, 4.14313473, 4.30406509, 3.55534806]])

In [92]:
mul

array([[82, 53, 46, 52, 34],
       [75, 68, 40, 16, 19],
       [78, 54, 19, 36, 72],
       [57, 61, 65, 41, 45],
       [14, 54, 63, 74, 35]], dtype=int32)

# Rounding Functions
- `np.round()`  :: Rounds values to the nearest integer
- `np.floor()`  :: Rounds values down to the nearest integer( towardsNegative)
- `np.ceil()`   :: Rounds values up to the nearest integer (towards positive infinity)

In [107]:
np.round(23.45555,2) # Wecan able ton give how many decimals should we give
np.round(23.45555)  # prints only  decimal befor epoints


np.float64(23.46)

np.float64(23.0)

In [106]:
np.floor(-23.45555)   # towards mainly negative round off +(-1)
np.ceil(23.45555)  # towards maily positive round off +(1)

np.float64(-24.0)

np.float64(24.0)

# SORTING THE ARRAYS 

In [124]:
random.seed(45)
mul=np.random.randint(12,85,(5,5))
mul

array([[61, 38, 48, 15, 27],
       [39, 16, 51, 77, 43],
       [73, 22, 15, 34, 43],
       [35, 67, 19, 41, 64],
       [12, 35, 81, 60, 34]], dtype=int32)

In [128]:
np.sort(mul) # Each row is sorted in ascending order
np.sort(mul, axis=0) # The values in each column are sorted top to bottom.
np.sort(mul, axis=1) # This is explicit row-wise sorting, same as the default.

array([[15, 27, 38, 48, 61],
       [16, 39, 43, 51, 77],
       [15, 22, 34, 43, 73],
       [19, 35, 41, 64, 67],
       [12, 34, 35, 60, 81]], dtype=int32)

array([[12, 16, 15, 15, 27],
       [35, 22, 19, 34, 34],
       [39, 35, 48, 41, 43],
       [61, 38, 51, 60, 43],
       [73, 67, 81, 77, 64]], dtype=int32)

array([[15, 27, 38, 48, 61],
       [16, 39, 43, 51, 77],
       [15, 22, 34, 43, 73],
       [19, 35, 41, 64, 67],
       [12, 34, 35, 60, 81]], dtype=int32)

In [127]:
x=mul.copy()
x.sort(axis=1)
x

array([[15, 27, 38, 48, 61],
       [16, 39, 43, 51, 77],
       [15, 22, 34, 43, 73],
       [19, 35, 41, 64, 67],
       [12, 34, 35, 60, 81]], dtype=int32)

# Commparision operators

In [143]:
arr1=np.random.randint(45,55,(5,5))
arr2=np.random.randint(45,50,(5,5))
arr1
arr2

array([[47, 48, 46, 51, 54],
       [51, 45, 45, 45, 50],
       [52, 46, 48, 49, 52],
       [47, 49, 49, 48, 47],
       [45, 47, 51, 47, 51]], dtype=int32)

array([[45, 48, 47, 46, 46],
       [45, 47, 47, 47, 45],
       [46, 47, 47, 45, 45],
       [48, 47, 48, 48, 48],
       [48, 48, 45, 46, 49]], dtype=int32)

In [144]:
arr1 == arr2 #same values returns true 

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False]])

In [145]:
arr1==47

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False,  True],
       [False,  True, False,  True, False]])

In [147]:
arr1[arr1>47]

array([48, 51, 54, 51, 50, 52, 48, 49, 52, 49, 49, 48, 51, 51],
      dtype=int32)

## Append and Concatinate 

`np.append()`

- Used to add values[every]  to the end of an array.

`np.concatenate()`

- Used to join two or more arrays together.

- Requires the arrays to have the same shape along the axis being concatenated.

In [174]:
arr1 
arr2=np.array([25,66,87,94,100])
arr2

array([[47, 48, 46, 51, 54],
       [51, 45, 45, 45, 50],
       [52, 46, 48, 49, 52],
       [47, 49, 49, 48, 47],
       [45, 47, 51, 47, 51]], dtype=int32)

array([ 25,  66,  87,  94, 100])

In [150]:
np.append(arr1,arr2) #appends the each and every value to array returns 1-D array

array([ 47,  48,  46,  51,  54,  51,  45,  45,  45,  50,  52,  46,  48,
        49,  52,  47,  49,  49,  48,  47,  45,  47,  51,  47,  51,  25,
        66,  87,  94, 100])

In [175]:
np.concatenate((arr1,arr2),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [153]:
arr1.shape
arr2.shape   #show shape must be match

(5, 5)

(5,)

In [164]:
a=np.random.randint(1,10,(2,2))
b=np.random.randint(10,20,(2,2))

In [166]:
a
b

array([[9, 1],
       [2, 8]], dtype=int32)

array([[17, 11],
       [13, 16]], dtype=int32)

In [172]:
np.concatenate((a,b),axis=0)
np.concatenate((a,b),axis=1)

array([[ 9,  1],
       [ 2,  8],
       [17, 11],
       [13, 16]], dtype=int32)

array([[ 9,  1, 17, 11],
       [ 2,  8, 13, 16]], dtype=int32)

# Stacking of arrays
-	Vertical stacking(row wise) using vstack()
-	Horizontal stacking(column wise) using hstack()
-	Depth wise stacking(along third axis) using dstack()
-                  and
- ` np.stack((a,b)) `   converts Separate  2d arrays into rows colums remains unchages  2d array
- `np.dstack((a,b))` seperate arrays into 3d array 1 rows of each sub array as 1st colum  new sub array vice versa

In [177]:
A = np.arange(1,13).reshape(3,4)
B = np.arange(1,9).reshape(2,4)
C = np.arange(1,7).reshape(3,2)
D = np.arange(10,22).reshape(3,4)

print(A, B, C,D, sep = "\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]]

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [183]:
np.vstack((A,B))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [185]:
np.hstack((A,C))

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [187]:
a
b

array([[9, 1],
       [2, 8]], dtype=int32)

array([[17, 11],
       [13, 16]], dtype=int32)

## `stack` converts Separate  2d arrays into rows colums remains unchages  2d array

In [190]:
np.stack((a,b))  #-> converts Separate  2d arrays into rows colums remains unchages  2d array

array([[[ 9,  1],
        [ 2,  8]],

       [[17, 11],
        [13, 16]]], dtype=int32)

## `depth` converts seperate arrays into 3ad array 1 rows of each sub array as 1st colum  new sub array vice versa

In [191]:
np.dstack((a,b)) #-> converts seperate arrays into 3ad array 1 rows of each sub array as 1st colum  new sub array vice versa

array([[[ 9, 17],
        [ 1, 11]],

       [[ 2, 13],
        [ 8, 16]]], dtype=int32)

# 🧩 Splitting of Arrays in NumPy

Splitting means dividing one array into multiple sub-arrays.

### 📌 Types of Splitting
- **`np.split()`** → Divides an array into equal parts along a given axis.  
- **`np.hsplit()`** → Splits horizontally (column-wise).  
- **`np.vsplit()`** → Splits vertically (row-wise).  
- **`np.dsplit()`** → Splits along the depth (3rd axis).  

✅ Use when you want to break arrays into smaller chunks for processing.


In [193]:
bigarr=np.random.randint(1,100,(8,8))
bigarr

array([[81, 84, 95, 22,  7, 23, 80, 75],
       [72, 19, 34, 72, 36, 41, 93, 12],
       [20, 25, 76, 74, 71, 57, 20, 60],
       [57, 30, 40, 78, 21,  8,  4, 74],
       [49, 87, 64, 30, 61, 35, 89, 32],
       [75, 51, 45, 76, 37, 12, 73, 45],
       [20, 73, 24, 16, 14, 70, 82, 27],
       [81, 22, 83, 25, 45, 60, 99, 89]], dtype=int32)

# # 🔑 Rule for Splitting Arrays

If you want to split an array into *n* parts,  
then *n* must be a **factor of the array size along that axis**.  

👉 Example:  
- Array of size 6 → can be split into 2, 3, or 6 equal parts.  
- Array of size 8 → can be split into 2, 4, or 8 equal parts.  
- If the split number is **not a factor**, NumPy will throw an error.


In [195]:
bigarr.shape

(8, 8)

In [199]:
np.split(bigarr,2) # here 2 is  array will be divided into N equal arrays 


[array([[81, 84, 95, 22,  7, 23, 80, 75],
        [72, 19, 34, 72, 36, 41, 93, 12],
        [20, 25, 76, 74, 71, 57, 20, 60],
        [57, 30, 40, 78, 21,  8,  4, 74]], dtype=int32),
 array([[49, 87, 64, 30, 61, 35, 89, 32],
        [75, 51, 45, 76, 37, 12, 73, 45],
        [20, 73, 24, 16, 14, 70, 82, 27],
        [81, 22, 83, 25, 45, 60, 99, 89]], dtype=int32)]

In [201]:
np.vsplit(bigarr,4) #vertical wise divided into 4 diff partsAa

[array([[81, 84, 95, 22,  7, 23, 80, 75],
        [72, 19, 34, 72, 36, 41, 93, 12]], dtype=int32),
 array([[20, 25, 76, 74, 71, 57, 20, 60],
        [57, 30, 40, 78, 21,  8,  4, 74]], dtype=int32),
 array([[49, 87, 64, 30, 61, 35, 89, 32],
        [75, 51, 45, 76, 37, 12, 73, 45]], dtype=int32),
 array([[20, 73, 24, 16, 14, 70, 82, 27],
        [81, 22, 83, 25, 45, 60, 99, 89]], dtype=int32)]

In [203]:
np.hsplit(bigarr,4)

[array([[81, 84],
        [72, 19],
        [20, 25],
        [57, 30],
        [49, 87],
        [75, 51],
        [20, 73],
        [81, 22]], dtype=int32),
 array([[95, 22],
        [34, 72],
        [76, 74],
        [40, 78],
        [64, 30],
        [45, 76],
        [24, 16],
        [83, 25]], dtype=int32),
 array([[ 7, 23],
        [36, 41],
        [71, 57],
        [21,  8],
        [61, 35],
        [37, 12],
        [14, 70],
        [45, 60]], dtype=int32),
 array([[80, 75],
        [93, 12],
        [20, 60],
        [ 4, 74],
        [89, 32],
        [73, 45],
        [82, 27],
        [99, 89]], dtype=int32)]

In [202]:
bigarr

array([[81, 84, 95, 22,  7, 23, 80, 75],
       [72, 19, 34, 72, 36, 41, 93, 12],
       [20, 25, 76, 74, 71, 57, 20, 60],
       [57, 30, 40, 78, 21,  8,  4, 74],
       [49, 87, 64, 30, 61, 35, 89, 32],
       [75, 51, 45, 76, 37, 12, 73, 45],
       [20, 73, 24, 16, 14, 70, 82, 27],
       [81, 22, 83, 25, 45, 60, 99, 89]], dtype=int32)

## Array Broadcasting
- Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes by stretching 

In [215]:
arr1

array([[47, 48, 46, 51, 54],
       [51, 45, 45, 45, 50],
       [52, 46, 48, 49, 52],
       [47, 49, 49, 48, 47],
       [45, 47, 51, 47, 51]], dtype=int32)

In [216]:
arr2=np.arange(5)
arr2

array([0, 1, 2, 3, 4])

In [220]:
#ScALAR
arr2+10

array([10, 11, 12, 13, 14])

### 2D array + 1D array

In [217]:
np.add(arr1,arr2) 

array([[47, 49, 48, 54, 58],
       [51, 46, 47, 48, 54],
       [52, 47, 50, 52, 56],
       [47, 50, 51, 51, 51],
       [45, 48, 53, 50, 55]])

In [218]:
np.subtract(arr1,arr2) 

array([[47, 47, 44, 48, 50],
       [51, 44, 43, 42, 46],
       [52, 45, 46, 46, 48],
       [47, 48, 47, 45, 43],
       [45, 46, 49, 44, 47]])

In [219]:
np.multiply(arr1,arr2) 

array([[  0,  48,  92, 153, 216],
       [  0,  45,  90, 135, 200],
       [  0,  46,  96, 147, 208],
       [  0,  49,  98, 144, 188],
       [  0,  47, 102, 141, 204]])